package defpackage;

/* compiled from: Twttr */
/* renamed from: bdd */
public final class bdd {
    public static final int[] ActionBar;
    public static final int[] ActionBarLayout;
    public static final int ActionBarLayout_android_layout_gravity = 0;
    public static final int ActionBar_background = 10;
    public static final int ActionBar_backgroundSplit = 12;
    public static final int ActionBar_backgroundStacked = 11;
    public static final int ActionBar_contentInsetEnd = 21;
    public static final int ActionBar_contentInsetLeft = 22;
    public static final int ActionBar_contentInsetRight = 23;
    public static final int ActionBar_contentInsetStart = 20;
    public static final int ActionBar_customNavigationLayout = 13;
    public static final int ActionBar_displayOptions = 3;
    public static final int ActionBar_divider = 9;
    public static final int ActionBar_elevation = 24;
    public static final int ActionBar_height = 0;
    public static final int ActionBar_hideOnContentScroll = 19;
    public static final int ActionBar_homeAsUpIndicator = 26;
    public static final int ActionBar_homeLayout = 14;
    public static final int ActionBar_icon = 7;
    public static final int ActionBar_indeterminateProgressStyle = 16;
    public static final int ActionBar_itemPadding = 18;
    public static final int ActionBar_logo = 8;
    public static final int ActionBar_navigationMode = 2;
    public static final int ActionBar_popupTheme = 25;
    public static final int ActionBar_progressBarPadding = 17;
    public static final int ActionBar_progressBarStyle = 15;
    public static final int ActionBar_subtitle = 4;
    public static final int ActionBar_subtitleTextStyle = 6;
    public static final int ActionBar_title = 1;
    public static final int ActionBar_titleTextStyle = 5;
    public static final int[] ActionMenuItemView;
    public static final int ActionMenuItemView_android_minWidth = 0;
    public static final int[] ActionMenuView;
    public static final int[] ActionMode;
    public static final int ActionMode_background = 3;
    public static final int ActionMode_backgroundSplit = 4;
    public static final int ActionMode_closeItemLayout = 5;
    public static final int ActionMode_height = 0;
    public static final int ActionMode_subtitleTextStyle = 2;
    public static final int ActionMode_titleTextStyle = 1;
    public static final int[] ActionPromptView;
    public static final int ActionPromptView_actionPromptBackgroundColor = 1;
    public static final int ActionPromptView_actionPromptPointerHeight = 0;
    public static final int ActionPromptView_actionPromptPointerRadius = 2;
    public static final int[] ActivityChooserView;
    public static final int ActivityChooserView_expandActivityOverflowButtonDrawable = 1;
    public static final int ActivityChooserView_initialActivityCount = 0;
    public static final int[] AdsAttrs;
    public static final int AdsAttrs_adSize = 0;
    public static final int AdsAttrs_adSizes = 1;
    public static final int AdsAttrs_adUnitId = 2;
    public static final int[] AlertDialog;
    public static final int AlertDialog_android_layout = 0;
    public static final int AlertDialog_buttonPanelSideLayout = 1;
    public static final int AlertDialog_listItemLayout = 5;
    public static final int AlertDialog_listLayout = 2;
    public static final int AlertDialog_multiChoiceItemLayout = 3;
    public static final int AlertDialog_singleChoiceItemLayout = 4;
    public static final int[] AnimatedGifView;
    public static final int AnimatedGifView_GifBackgroundColor = 2;
    public static final int AnimatedGifView_MinimumDurationMs = 1;
    public static final int AnimatedGifView_MinimumRepeatCount = 0;
    public static final int[] AppBarLayout;
    public static final int[] AppBarLayout_LayoutParams;
    public static final int AppBarLayout_LayoutParams_layout_scrollFlags = 0;
    public static final int AppBarLayout_LayoutParams_layout_scrollInterpolator = 1;
    public static final int AppBarLayout_android_background = 0;
    public static final int AppBarLayout_elevation = 1;
    public static final int AppBarLayout_expanded = 2;
    public static final int[] AppCompatImageView;
    public static final int AppCompatImageView_android_src = 0;
    public static final int AppCompatImageView_srcCompat = 1;
    public static final int[] AppCompatTextView;
    public static final int AppCompatTextView_android_textAppearance = 0;
    public static final int AppCompatTextView_textAllCaps = 1;
    public static final int[] AppCompatTheme;
    public static final int AppCompatTheme_actionBarDivider = 23;
    public static final int AppCompatTheme_actionBarItemBackground = 24;
    public static final int AppCompatTheme_actionBarPopupTheme = 17;
    public static final int AppCompatTheme_actionBarSize = 22;
    public static final int AppCompatTheme_actionBarSplitStyle = 19;
    public static final int AppCompatTheme_actionBarStyle = 18;
    public static final int AppCompatTheme_actionBarTabBarStyle = 13;
    public static final int AppCompatTheme_actionBarTabStyle = 12;
    public static final int AppCompatTheme_actionBarTabTextStyle = 14;
    public static final int AppCompatTheme_actionBarTheme = 20;
    public static final int AppCompatTheme_actionBarWidgetTheme = 21;
    public static final int AppCompatTheme_actionButtonStyle = 49;
    public static final int AppCompatTheme_actionDropDownStyle = 45;
    public static final int AppCompatTheme_actionMenuTextAppearance = 25;
    public static final int AppCompatTheme_actionMenuTextColor = 26;
    public static final int AppCompatTheme_actionModeBackground = 29;
    public static final int AppCompatTheme_actionModeCloseButtonStyle = 28;
    public static final int AppCompatTheme_actionModeCloseDrawable = 31;
    public static final int AppCompatTheme_actionModeCopyDrawable = 33;
    public static final int AppCompatTheme_actionModeCutDrawable = 32;
    public static final int AppCompatTheme_actionModeFindDrawable = 37;
    public static final int AppCompatTheme_actionModePasteDrawable = 34;
    public static final int AppCompatTheme_actionModePopupWindowStyle = 39;
    public static final int AppCompatTheme_actionModeSelectAllDrawable = 35;
    public static final int AppCompatTheme_actionModeShareDrawable = 36;
    public static final int AppCompatTheme_actionModeSplitBackground = 30;
    public static final int AppCompatTheme_actionModeStyle = 27;
    public static final int AppCompatTheme_actionModeWebSearchDrawable = 38;
    public static final int AppCompatTheme_actionOverflowButtonStyle = 15;
    public static final int AppCompatTheme_actionOverflowMenuStyle = 16;
    public static final int AppCompatTheme_activityChooserViewStyle = 57;
    public static final int AppCompatTheme_alertDialogButtonGroupStyle = 92;
    public static final int AppCompatTheme_alertDialogCenterButtons = 93;
    public static final int AppCompatTheme_alertDialogStyle = 91;
    public static final int AppCompatTheme_alertDialogTheme = 94;
    public static final int AppCompatTheme_android_windowAnimationStyle = 1;
    public static final int AppCompatTheme_android_windowIsFloating = 0;
    public static final int AppCompatTheme_autoCompleteTextViewStyle = 99;
    public static final int AppCompatTheme_borderlessButtonStyle = 54;
    public static final int AppCompatTheme_buttonBarButtonStyle = 51;
    public static final int AppCompatTheme_buttonBarNegativeButtonStyle = 97;
    public static final int AppCompatTheme_buttonBarNeutralButtonStyle = 98;
    public static final int AppCompatTheme_buttonBarPositiveButtonStyle = 96;
    public static final int AppCompatTheme_buttonBarStyle = 50;
    public static final int AppCompatTheme_buttonStyle = 100;
    public static final int AppCompatTheme_buttonStyleSmall = 101;
    public static final int AppCompatTheme_checkboxStyle = 102;
    public static final int AppCompatTheme_checkedTextViewStyle = 103;
    public static final int AppCompatTheme_colorAccent = 84;
    public static final int AppCompatTheme_colorButtonNormal = 88;
    public static final int AppCompatTheme_colorControlActivated = 86;
    public static final int AppCompatTheme_colorControlHighlight = 87;
    public static final int AppCompatTheme_colorControlNormal = 85;
    public static final int AppCompatTheme_colorPrimary = 82;
    public static final int AppCompatTheme_colorPrimaryDark = 83;
    public static final int AppCompatTheme_colorSwitchThumbNormal = 89;
    public static final int AppCompatTheme_controlBackground = 90;
    public static final int AppCompatTheme_dialogPreferredPadding = 43;
    public static final int AppCompatTheme_dialogTheme = 42;
    public static final int AppCompatTheme_dividerHorizontal = 56;
    public static final int AppCompatTheme_dividerVertical = 55;
    public static final int AppCompatTheme_dropDownListViewStyle = 74;
    public static final int AppCompatTheme_dropdownListPreferredItemHeight = 46;
    public static final int AppCompatTheme_editTextBackground = 63;
    public static final int AppCompatTheme_editTextColor = 62;
    public static final int AppCompatTheme_editTextStyle = 104;
    public static final int AppCompatTheme_homeAsUpIndicator = 48;
    public static final int AppCompatTheme_imageButtonStyle = 64;
    public static final int AppCompatTheme_listChoiceBackgroundIndicator = 81;
    public static final int AppCompatTheme_listDividerAlertDialog = 44;
    public static final int AppCompatTheme_listPopupWindowStyle = 75;
    public static final int AppCompatTheme_listPreferredItemHeight = 69;
    public static final int AppCompatTheme_listPreferredItemHeightLarge = 71;
    public static final int AppCompatTheme_listPreferredItemHeightSmall = 70;
    public static final int AppCompatTheme_listPreferredItemPaddingLeft = 72;
    public static final int AppCompatTheme_listPreferredItemPaddingRight = 73;
    public static final int AppCompatTheme_panelBackground = 78;
    public static final int AppCompatTheme_panelMenuListTheme = 80;
    public static final int AppCompatTheme_panelMenuListWidth = 79;
    public static final int AppCompatTheme_popupMenuStyle = 60;
    public static final int AppCompatTheme_popupWindowStyle = 61;
    public static final int AppCompatTheme_radioButtonStyle = 105;
    public static final int AppCompatTheme_ratingBarStyle = 106;
    public static final int AppCompatTheme_ratingBarStyleIndicator = 107;
    public static final int AppCompatTheme_ratingBarStyleSmall = 108;
    public static final int AppCompatTheme_searchViewStyle = 68;
    public static final int AppCompatTheme_seekBarStyle = 109;
    public static final int AppCompatTheme_selectableItemBackground = 52;
    public static final int AppCompatTheme_selectableItemBackgroundBorderless = 53;
    public static final int AppCompatTheme_spinnerDropDownItemStyle = 47;
    public static final int AppCompatTheme_spinnerStyle = 110;
    public static final int AppCompatTheme_switchStyle = 111;
    public static final int AppCompatTheme_textAppearanceLargePopupMenu = 40;
    public static final int AppCompatTheme_textAppearanceListItem = 76;
    public static final int AppCompatTheme_textAppearanceListItemSmall = 77;
    public static final int AppCompatTheme_textAppearanceSearchResultSubtitle = 66;
    public static final int AppCompatTheme_textAppearanceSearchResultTitle = 65;
    public static final int AppCompatTheme_textAppearanceSmallPopupMenu = 41;
    public static final int AppCompatTheme_textColorAlertDialogListItem = 95;
    public static final int AppCompatTheme_textColorSearchUrl = 67;
    public static final int AppCompatTheme_toolbarNavigationButtonStyle = 59;
    public static final int AppCompatTheme_toolbarStyle = 58;
    public static final int AppCompatTheme_windowActionBar = 2;
    public static final int AppCompatTheme_windowActionBarOverlay = 4;
    public static final int AppCompatTheme_windowActionModeOverlay = 5;
    public static final int AppCompatTheme_windowFixedHeightMajor = 9;
    public static final int AppCompatTheme_windowFixedHeightMinor = 7;
    public static final int AppCompatTheme_windowFixedWidthMajor = 6;
    public static final int AppCompatTheme_windowFixedWidthMinor = 8;
    public static final int AppCompatTheme_windowMinWidthMajor = 10;
    public static final int AppCompatTheme_windowMinWidthMinor = 11;
    public static final int AppCompatTheme_windowNoTitle = 3;
    public static final int[] AspectRatioFrameLayout;
    public static final int AspectRatioFrameLayout_aspect_ratio = 0;
    public static final int AspectRatioFrameLayout_max_aspect_ratio = 2;
    public static final int AspectRatioFrameLayout_max_height = 4;
    public static final int AspectRatioFrameLayout_max_width = 3;
    public static final int AspectRatioFrameLayout_min_aspect_ratio = 1;
    public static final int AspectRatioFrameLayout_scaleMode = 5;
    public static final int[] BackgroundImageView;
    public static final int BackgroundImageView_crossfadeDuration = 1;
    public static final int BackgroundImageView_filterColor = 3;
    public static final int BackgroundImageView_filterMaxOpacity = 2;
    public static final int BackgroundImageView_overlayDrawable = 0;
    public static final int[] BadgeIndicator;
    public static final int BadgeIndicator_badgeMode = 10;
    public static final int BadgeIndicator_circleDrawable = 7;
    public static final int BadgeIndicator_circleMarginRight = 9;
    public static final int BadgeIndicator_circleMarginTop = 8;
    public static final int BadgeIndicator_indicatorDrawable = 0;
    public static final int BadgeIndicator_indicatorMarginBottom = 1;
    public static final int BadgeIndicator_numberBackground = 2;
    public static final int BadgeIndicator_numberColor = 3;
    public static final int BadgeIndicator_numberMinHeight = 6;
    public static final int BadgeIndicator_numberMinWidth = 5;
    public static final int BadgeIndicator_numberTextSize = 4;
    public static final int[] BadgeView;
    public static final int BadgeView_android_lineSpacingExtra = 1;
    public static final int BadgeView_android_lineSpacingMultiplier = 2;
    public static final int BadgeView_android_textSize = 0;
    public static final int BadgeView_badgeSpacing = 3;
    public static final int BadgeView_contentColor = 4;
    public static final int BadgeView_showBadge = 5;
    public static final int[] BaseMediaImageView;
    public static final int BaseMediaImageView_defaultDrawable = 0;
    public static final int BaseMediaImageView_errorDrawable = 1;
    public static final int BaseMediaImageView_imageType = 2;
    public static final int BaseMediaImageView_scaleType = 4;
    public static final int BaseMediaImageView_updateOnResize = 3;
    public static final int[] BottomSheetBehavior_Params;
    public static final int BottomSheetBehavior_Params_behavior_hideable = 1;
    public static final int BottomSheetBehavior_Params_behavior_peekHeight = 0;
    public static final int[] ButtonBarLayout;
    public static final int ButtonBarLayout_allowStacking = 0;
    public static final int[] CardView;
    public static final int CardView_elementPressedColor = 0;
    public static final int CardView_imagePlaceholderColor = 1;
    public static final int CardView_playerOverlay = 2;
    public static final int[] CellLayout_Layout;
    public static final int CellLayout_Layout_android_layout_gravity = 0;
    public static final int[] ChannelView;
    public static final int ChannelView_ps__heartsMarginFactor = 1;
    public static final int ChannelView_ps__includeComposer = 0;
    public static final int[] ClipRowView;
    public static final int ClipRowView_insetDividerColor = 4;
    public static final int ClipRowView_insetDividerHeight = 3;
    public static final int ClipRowView_insetHeight = 2;
    public static final int ClipRowView_insetPaddingStart = 0;
    public static final int ClipRowView_insetWidth = 1;
    public static final int[] CollapsingAppBarLayout_LayoutParams;
    public static final int CollapsingAppBarLayout_LayoutParams_layout_collapseMode = 0;
    public static final int CollapsingAppBarLayout_LayoutParams_layout_collapseParallaxMultiplier = 1;
    public static final int[] CollapsingToolbarLayout;
    public static final int CollapsingToolbarLayout_collapsedTitleGravity = 11;
    public static final int CollapsingToolbarLayout_collapsedTitleTextAppearance = 7;
    public static final int CollapsingToolbarLayout_contentScrim = 8;
    public static final int CollapsingToolbarLayout_expandedTitleGravity = 12;
    public static final int CollapsingToolbarLayout_expandedTitleMargin = 1;
    public static final int CollapsingToolbarLayout_expandedTitleMarginBottom = 5;
    public static final int CollapsingToolbarLayout_expandedTitleMarginEnd = 4;
    public static final int CollapsingToolbarLayout_expandedTitleMarginStart = 2;
    public static final int CollapsingToolbarLayout_expandedTitleMarginTop = 3;
    public static final int CollapsingToolbarLayout_expandedTitleTextAppearance = 6;
    public static final int CollapsingToolbarLayout_statusBarScrim = 9;
    public static final int CollapsingToolbarLayout_title = 0;
    public static final int CollapsingToolbarLayout_titleEnabled = 13;
    public static final int CollapsingToolbarLayout_toolbarId = 10;
    public static final int[] CompoundButton;
    public static final int CompoundButton_android_button = 0;
    public static final int CompoundButton_buttonTint = 1;
    public static final int CompoundButton_buttonTintMode = 2;
    public static final int[] CompoundDrawableAnimButton;
    public static final int CompoundDrawableAnimButton_state_animate_to_checked = 0;
    public static final int CompoundDrawableAnimButton_state_animate_to_default = 1;
    public static final int CompoundDrawableAnimButton_transition_duration = 2;
    public static final int[] CoordinatorLayout;
    public static final int[] CoordinatorLayout_LayoutParams;
    public static final int CoordinatorLayout_LayoutParams_android_layout_gravity = 0;
    public static final int CoordinatorLayout_LayoutParams_layout_anchor = 2;
    public static final int CoordinatorLayout_LayoutParams_layout_anchorGravity = 4;
    public static final int CoordinatorLayout_LayoutParams_layout_behavior = 1;
    public static final int CoordinatorLayout_LayoutParams_layout_keyline = 3;
    public static final int CoordinatorLayout_keylines = 0;
    public static final int CoordinatorLayout_statusBarBackground = 1;
    public static final int[] CropContainerView;
    public static final int CropContainerView_cropper_cornerRadius = 2;
    public static final int CropContainerView_cropper_cropAspectRatio = 1;
    public static final int CropContainerView_cropper_cropWidth = 0;
    public static final int CropContainerView_cropper_overlayColor = 5;
    public static final int CropContainerView_cropper_strokeColor = 4;
    public static final int CropContainerView_cropper_strokeWidth = 3;
    public static final int[] CroppableImageView;
    public static final int CroppableImageView_cropRectPadding = 1;
    public static final int CroppableImageView_cropRectStrokeColor = 2;
    public static final int CroppableImageView_cropRectStrokeWidth = 3;
    public static final int CroppableImageView_cropShadowColor = 4;
    public static final int CroppableImageView_draggableCorners = 5;
    public static final int CroppableImageView_gridColor = 7;
    public static final int CroppableImageView_showGrid = 6;
    public static final int CroppableImageView_toolbarMargin = 0;
    public static final int[] DesignTheme;
    public static final int DesignTheme_bottomSheetDialogTheme = 0;
    public static final int DesignTheme_bottomSheetStyle = 1;
    public static final int DesignTheme_textColorError = 2;
    public static final int[] DismissableOverlayImageView;
    public static final int DismissableOverlayImageView_dismissOverlayDrawable = 0;
    public static final int[] DockLayout;
    public static final int DockLayout_autoUnlock = 6;
    public static final int DockLayout_bottomDockId = 1;
    public static final int DockLayout_bottomPeek = 4;
    public static final int DockLayout_disableAccessibilityLockOverride = 7;
    public static final int DockLayout_scrollDrive = 5;
    public static final int DockLayout_topDockId = 0;
    public static final int DockLayout_topPeek = 3;
    public static final int DockLayout_turtle = 2;
    public static final int[] DrawerArrowToggle;
    public static final int DrawerArrowToggle_arrowHeadLength = 4;
    public static final int DrawerArrowToggle_arrowShaftLength = 5;
    public static final int DrawerArrowToggle_barLength = 6;
    public static final int DrawerArrowToggle_color = 0;
    public static final int DrawerArrowToggle_drawableSize = 2;
    public static final int DrawerArrowToggle_gapBetweenBars = 3;
    public static final int DrawerArrowToggle_spinBars = 1;
    public static final int DrawerArrowToggle_thickness = 7;
    public static final int[] EditableMediaView;
    public static final int EditableMediaView_animatedGifViewLayout = 2;
    public static final int EditableMediaView_itemPadding = 1;
    public static final int EditableMediaView_layout = 3;
    public static final int EditableMediaView_playerOverlay = 0;
    public static final int[] FadeInTextView;
    public static final int FadeInTextView_android_duration = 2;
    public static final int FadeInTextView_android_textColor = 1;
    public static final int FadeInTextView_android_textSize = 0;
    public static final int FadeInTextView_texts = 3;
    public static final int[] FixedSizeImageView;
    public static final int FixedSizeImageView_fixedSize = 0;
    public static final int[] FloatingActionButton;
    public static final int FloatingActionButton_backgroundTint = 6;
    public static final int FloatingActionButton_backgroundTintMode = 7;
    public static final int FloatingActionButton_borderWidth = 4;
    public static final int FloatingActionButton_elevation = 0;
    public static final int FloatingActionButton_fabSize = 2;
    public static final int FloatingActionButton_pressedTranslationZ = 3;
    public static final int FloatingActionButton_rippleColor = 1;
    public static final int FloatingActionButton_useCompatPadding = 5;
    public static final int[] FlowLayout;
    public static final int[] FlowLayoutManagerLayout;
    public static final int FlowLayoutManagerLayout_ignoreParentPadding = 0;
    public static final int FlowLayout_horizontalSpacing = 0;
    public static final int FlowLayout_verticalSpacing = 1;
    public static final int[] ForegroundLinearLayout;
    public static final int ForegroundLinearLayout_android_foreground = 0;
    public static final int ForegroundLinearLayout_android_foregroundGravity = 1;
    public static final int ForegroundLinearLayout_foregroundInsidePadding = 2;
    public static final int[] GenericDraweeView;
    public static final int GenericDraweeView_actualImageScaleType = 11;
    public static final int GenericDraweeView_backgroundImage = 12;
    public static final int GenericDraweeView_fadeDuration = 0;
    public static final int GenericDraweeView_failureImage = 6;
    public static final int GenericDraweeView_failureImageScaleType = 7;
    public static final int GenericDraweeView_overlayImage = 13;
    public static final int GenericDraweeView_placeholderImage = 2;
    public static final int GenericDraweeView_placeholderImageScaleType = 3;
    public static final int GenericDraweeView_pressedStateOverlayImage = 14;
    public static final int GenericDraweeView_progressBarAutoRotateInterval = 10;
    public static final int GenericDraweeView_progressBarImage = 8;
    public static final int GenericDraweeView_progressBarImageScaleType = 9;
    public static final int GenericDraweeView_retryImage = 4;
    public static final int GenericDraweeView_retryImageScaleType = 5;
    public static final int GenericDraweeView_roundAsCircle = 15;
    public static final int GenericDraweeView_roundBottomLeft = 20;
    public static final int GenericDraweeView_roundBottomRight = 19;
    public static final int GenericDraweeView_roundTopLeft = 17;
    public static final int GenericDraweeView_roundTopRight = 18;
    public static final int GenericDraweeView_roundWithOverlayColor = 21;
    public static final int GenericDraweeView_roundedCornerRadius = 16;
    public static final int GenericDraweeView_roundingBorderColor = 23;
    public static final int GenericDraweeView_roundingBorderWidth = 22;
    public static final int GenericDraweeView_viewAspectRatio = 1;
    public static final int[] GridLinesView;
    public static final int GridLinesView_grid_line_color = 4;
    public static final int GridLinesView_grid_line_width = 0;
    public static final int GridLinesView_line_stroke_color = 5;
    public static final int GridLinesView_line_stroke_width = 1;
    public static final int GridLinesView_number_of_horizontal_lines = 2;
    public static final int GridLinesView_number_of_vertical_lines = 3;
    public static final int[] GroupedRowView;
    public static final int GroupedRowView_borderColor = 5;
    public static final int GroupedRowView_borderHeight = 6;
    public static final int GroupedRowView_cardStyle = 0;
    public static final int GroupedRowView_fillColor = 8;
    public static final int GroupedRowView_gapSize = 7;
    public static final int GroupedRowView_groupStyle = 1;
    public static final int GroupedRowView_hideBorder = 4;
    public static final int GroupedRowView_hideDivider = 3;
    public static final int GroupedRowView_single = 2;
    public static final int[] HorizontalListView;
    public static final int HorizontalListView_dividerWidth = 1;
    public static final int HorizontalListView_edgePadding = 2;
    public static final int HorizontalListView_fillMode = 7;
    public static final int HorizontalListView_fillWidthHeightRatio = 3;
    public static final int HorizontalListView_leftFadeInDrawable = 8;
    public static final int HorizontalListView_listDivider = 0;
    public static final int HorizontalListView_rightFadeInDrawable = 9;
    public static final int HorizontalListView_scrollDrawable = 5;
    public static final int HorizontalListView_scrollHeight = 6;
    public static final int HorizontalListView_scrollOffset = 4;
    public static final int[] InlineActionBar;
    public static final int InlineActionBar_displayBorder = 0;
    public static final int InlineActionBar_inlineActionBorderWidth = 1;
    public static final int[] InlineActionTextStyle;
    public static final int InlineActionTextStyle_textBackground = 1;
    public static final int InlineActionTextStyle_textColor = 0;
    public static final int InlineActionTextStyle_textFontSize = 2;
    public static final int InlineActionTextStyle_textHorizontalPadding = 3;
    public static final int InlineActionTextStyle_textVerticalPadding = 4;
    public static final int[] InlineActionView;
    public static final int InlineActionView_badgeMaskWidth = 3;
    public static final int InlineActionView_badgeSidePadding = 4;
    public static final int InlineActionView_badgeTextStyle = 7;
    public static final int InlineActionView_iconPaddingBadgeMode = 2;
    public static final int InlineActionView_iconPaddingNormal = 1;
    public static final int InlineActionView_inlineActionDrawable = 0;
    public static final int InlineActionView_inlineActionLabelMargin = 5;
    public static final int InlineActionView_labelTextStyle = 8;
    public static final int InlineActionView_showLabel = 6;
    public static final int[] LinearLayoutCompat;
    public static final int[] LinearLayoutCompat_Layout;
    public static final int LinearLayoutCompat_Layout_android_layout_gravity = 0;
    public static final int LinearLayoutCompat_Layout_android_layout_height = 2;
    public static final int LinearLayoutCompat_Layout_android_layout_weight = 3;
    public static final int LinearLayoutCompat_Layout_android_layout_width = 1;
    public static final int LinearLayoutCompat_android_baselineAligned = 2;
    public static final int LinearLayoutCompat_android_baselineAlignedChildIndex = 3;
    public static final int LinearLayoutCompat_android_gravity = 0;
    public static final int LinearLayoutCompat_android_orientation = 1;
    public static final int LinearLayoutCompat_android_weightSum = 4;
    public static final int LinearLayoutCompat_divider = 5;
    public static final int LinearLayoutCompat_dividerPadding = 8;
    public static final int LinearLayoutCompat_measureWithLargestChild = 6;
    public static final int LinearLayoutCompat_showDividers = 7;
    public static final int[] ListPopupWindow;
    public static final int ListPopupWindow_android_dropDownHorizontalOffset = 0;
    public static final int ListPopupWindow_android_dropDownVerticalOffset = 1;
    public static final int[] LoadingImageView;
    public static final int LoadingImageView_circleCrop = 2;
    public static final int LoadingImageView_imageAspectRatio = 1;
    public static final int LoadingImageView_imageAspectRatioAdjust = 0;
    public static final int[] MapAttrs;
    public static final int MapAttrs_ambientEnabled = 16;
    public static final int MapAttrs_cameraBearing = 1;
    public static final int MapAttrs_cameraTargetLat = 2;
    public static final int MapAttrs_cameraTargetLng = 3;
    public static final int MapAttrs_cameraTilt = 4;
    public static final int MapAttrs_cameraZoom = 5;
    public static final int MapAttrs_liteMode = 6;
    public static final int MapAttrs_mapType = 0;
    public static final int MapAttrs_uiCompass = 7;
    public static final int MapAttrs_uiMapToolbar = 15;
    public static final int MapAttrs_uiRotateGestures = 8;
    public static final int MapAttrs_uiScrollGestures = 9;
    public static final int MapAttrs_uiTiltGestures = 10;
    public static final int MapAttrs_uiZoomControls = 11;
    public static final int MapAttrs_uiZoomGestures = 12;
    public static final int MapAttrs_useViewLifecycle = 13;
    public static final int MapAttrs_zOrderOnTop = 14;
    public static final int[] MaskImageView;
    public static final int MaskImageView_ps__cornerRadius = 0;
    public static final int MaskImageView_ps__maskType = 1;
    public static final int[] MediaImageView;
    public static final int MediaImageView_fadeIn = 0;
    public static final int MediaImageView_loadingProgressBar = 3;
    public static final int MediaImageView_scaleFactor = 2;
    public static final int MediaImageView_singleImageView = 1;
    public static final int[] MenuGroup;
    public static final int MenuGroup_android_checkableBehavior = 5;
    public static final int MenuGroup_android_enabled = 0;
    public static final int MenuGroup_android_id = 1;
    public static final int MenuGroup_android_menuCategory = 3;
    public static final int MenuGroup_android_orderInCategory = 4;
    public static final int MenuGroup_android_visible = 2;
    public static final int[] MenuItem;
    public static final int MenuItem_actionLayout = 14;
    public static final int MenuItem_actionProviderClass = 16;
    public static final int MenuItem_actionViewClass = 15;
    public static final int MenuItem_android_alphabeticShortcut = 9;
    public static final int MenuItem_android_checkable = 11;
    public static final int MenuItem_android_checked = 3;
    public static final int MenuItem_android_enabled = 1;
    public static final int MenuItem_android_icon = 0;
    public static final int MenuItem_android_id = 2;
    public static final int MenuItem_android_menuCategory = 5;
    public static final int MenuItem_android_numericShortcut = 10;
    public static final int MenuItem_android_onClick = 12;
    public static final int MenuItem_android_orderInCategory = 6;
    public static final int MenuItem_android_title = 7;
    public static final int MenuItem_android_titleCondensed = 8;
    public static final int MenuItem_android_visible = 4;
    public static final int MenuItem_showAsAction = 13;
    public static final int[] MenuView;
    public static final int MenuView_android_headerBackground = 4;
    public static final int MenuView_android_horizontalDivider = 2;
    public static final int MenuView_android_itemBackground = 5;
    public static final int MenuView_android_itemIconDisabledAlpha = 6;
    public static final int MenuView_android_itemTextAppearance = 1;
    public static final int MenuView_android_verticalDivider = 3;
    public static final int MenuView_android_windowAnimationStyle = 0;
    public static final int MenuView_preserveIconSpacing = 7;
    public static final int[] NavItemView;
    public static final int NavItemView_badgeIndicatorStyle = 0;
    public static final int NavItemView_displayMode = 5;
    public static final int NavItemView_selectedTextStyle = 1;
    public static final int NavItemView_textColor = 2;
    public static final int NavItemView_textSize = 3;
    public static final int NavItemView_textStyle = 4;
    public static final int NavItemView_unselectedIconTint = 6;
    public static final int[] NavigationView;
    public static final int NavigationView_android_background = 0;
    public static final int NavigationView_android_fitsSystemWindows = 1;
    public static final int NavigationView_android_maxWidth = 2;
    public static final int NavigationView_elevation = 3;
    public static final int NavigationView_headerLayout = 9;
    public static final int NavigationView_itemBackground = 7;
    public static final int NavigationView_itemIconTint = 5;
    public static final int NavigationView_itemTextAppearance = 8;
    public static final int NavigationView_itemTextColor = 6;
    public static final int NavigationView_menu = 4;
    public static final int[] NotificationSocialProofStyle;
    public static final int NotificationSocialProofStyle_eventTypeFavoriteDrawable = 2;
    public static final int NotificationSocialProofStyle_eventTypeFavoritedMediaTagDrawable = 8;
    public static final int NotificationSocialProofStyle_eventTypeFavoritedMentionDrawable = 4;
    public static final int NotificationSocialProofStyle_eventTypeFavoritedRetweetDrawable = 3;
    public static final int NotificationSocialProofStyle_eventTypeFollowDrawable = 0;
    public static final int NotificationSocialProofStyle_eventTypeJoinedTwitterDrawable = 1;
    public static final int NotificationSocialProofStyle_eventTypeRetweetDrawable = 5;
    public static final int NotificationSocialProofStyle_eventTypeRetweetedMediaTagDrawable = 9;
    public static final int NotificationSocialProofStyle_eventTypeRetweetedMentionDrawable = 7;
    public static final int NotificationSocialProofStyle_eventTypeRetweetedRetweetDrawable = 6;
    public static final int[] PageableListView;
    public static final int PageableListView_defaultPosition = 3;
    public static final int PageableListView_loadingFooterLayout = 2;
    public static final int PageableListView_loadingHeaderDivider = 1;
    public static final int PageableListView_loadingHeaderLayout = 0;
    public static final int[] PillToggleButton;
    public static final int PillToggleButton_borderStrokeWidth = 0;
    public static final int PillToggleButton_checkDrawable = 5;
    public static final int PillToggleButton_plusDrawable = 6;
    public static final int PillToggleButton_selectedBackgroundColor = 3;
    public static final int PillToggleButton_selectedTextColor = 4;
    public static final int PillToggleButton_unselectedBorderColor = 1;
    public static final int PillToggleButton_unselectedTextColor = 2;
    public static final int[] PlayerView;
    public static final int PlayerView_ps__includeComposer = 0;
    public static final int[] PopupEditText;
    public static final int PopupEditText_popupMenuXOffset = 0;
    public static final int PopupEditText_popupMenuYOffset = 1;
    public static final int PopupEditText_showAsDropdown = 2;
    public static final int PopupEditText_showFullScreen = 3;
    public static final int PopupEditText_showPopupOnInitialFocus = 5;
    public static final int PopupEditText_stripHtml = 6;
    public static final int PopupEditText_threshold = 4;
    public static final int[] PopupSuggestionEditText;
    public static final int PopupSuggestionEditText_popupMenuXOffset = 0;
    public static final int PopupSuggestionEditText_popupMenuYOffset = 1;
    public static final int PopupSuggestionEditText_showAsDropdown = 2;
    public static final int PopupSuggestionEditText_showFullScreen = 3;
    public static final int[] PopupWindow;
    public static final int[] PopupWindowBackgroundState;
    public static final int PopupWindowBackgroundState_state_above_anchor = 0;
    public static final int PopupWindow_android_popupBackground = 0;
    public static final int PopupWindow_overlapAnchor = 1;
    public static final int[] ProfileCardView;
    public static final int ProfileCardView_profileCardAvatarSize = 0;
    public static final int ProfileCardView_profileCardBottomPadding = 1;
    public static final int ProfileCardView_profileDescriptionFontSize = 4;
    public static final int ProfileCardView_profileImageTopMarginRatio = 2;
    public static final int ProfileCardView_profileUserImageStrokeWidth = 3;
    public static final int[] ProgressLayout;
    public static final int ProgressLayout_android_max = 0;
    public static final int[] PromptView;
    public static final int PromptView_buttonText = 2;
    public static final int PromptView_isHeader = 4;
    public static final int PromptView_showDismiss = 3;
    public static final int PromptView_subtitleText = 1;
    public static final int PromptView_titleText = 0;
    public static final int[] PsImageView;
    public static final int PsImageView_ps__tint = 0;
    public static final int PsImageView_ps__toolTipOff = 2;
    public static final int PsImageView_ps__toolTipOn = 1;
    public static final int[] PsLoading;
    public static final int PsLoading_ps__halfHeight = 0;
    public static final int[] PsTextView;
    public static final int PsTextView_ps__font = 0;
    public static final int[] QuoteView;
    public static final int QuoteView_borderColor = 5;
    public static final int QuoteView_borderCornerRadius = 16;
    public static final int QuoteView_borderWidth = 4;
    public static final int QuoteView_bylineColor = 0;
    public static final int QuoteView_bylineSize = 1;
    public static final int QuoteView_compactMediaWidth = 9;
    public static final int QuoteView_contentColor = 2;
    public static final int QuoteView_contentPaddingTop = 14;
    public static final int QuoteView_contentSize = 3;
    public static final int QuoteView_interstitialBackgroundColor = 8;
    public static final int QuoteView_interstitialTextColor = 7;
    public static final int QuoteView_interstitialTextSize = 6;
    public static final int QuoteView_mediaDividerSize = 10;
    public static final int QuoteView_mediaPlaceholder = 11;
    public static final int QuoteView_mediaTextGap = 15;
    public static final int QuoteView_quoteViewHeaderStyle = 12;
    public static final int QuoteView_quoteViewReplyContextStyle = 13;
    public static final int QuoteView_sensitiveMediaCoverDrawable = 17;
    public static final int QuoteView_sensitiveMediaCoverSmallDrawable = 18;
    public static final int[] RecyclerView;
    public static final int RecyclerView_android_orientation = 0;
    public static final int RecyclerView_layoutManager = 1;
    public static final int RecyclerView_reverseLayout = 3;
    public static final int RecyclerView_spanCount = 2;
    public static final int RecyclerView_stackFromEnd = 4;
    public static final int[] RichImageView;
    public static final int RichImageView_cornerRadius = 0;
    public static final int RichImageView_cornerRadiusBottomLeft = 4;
    public static final int RichImageView_cornerRadiusBottomRight = 5;
    public static final int RichImageView_cornerRadiusTopLeft = 2;
    public static final int RichImageView_cornerRadiusTopRight = 3;
    public static final int RichImageView_overlayDrawable = 1;
    public static final int[] RoundedGroupedRowView;
    public static final int RoundedGroupedRowView_cardStyle = 0;
    public static final int RoundedGroupedRowView_cornerRadius = 1;
    public static final int RoundedGroupedRowView_dividerColor = 2;
    public static final int RoundedGroupedRowView_dividerHeight = 15;
    public static final int RoundedGroupedRowView_groupStyle = 3;
    public static final int RoundedGroupedRowView_inset = 9;
    public static final int RoundedGroupedRowView_insetBottom = 13;
    public static final int RoundedGroupedRowView_insetBottomFillColor = 14;
    public static final int RoundedGroupedRowView_insetLeft = 10;
    public static final int RoundedGroupedRowView_insetRight = 12;
    public static final int RoundedGroupedRowView_insetTop = 11;
    public static final int RoundedGroupedRowView_shadowColor = 4;
    public static final int RoundedGroupedRowView_shadowDx = 5;
    public static final int RoundedGroupedRowView_shadowDy = 6;
    public static final int RoundedGroupedRowView_shadowRadius = 7;
    public static final int RoundedGroupedRowView_single = 8;
    public static final int RoundedGroupedRowView_strokeColor = 16;
    public static final int RoundedGroupedRowView_strokeWidth = 17;
    public static final int[] SVGImageView;
    public static final int SVGImageView_svg = 0;
    public static final int[] ScrimInsetsFrameLayout;
    public static final int ScrimInsetsFrameLayout_insetForeground = 0;
    public static final int[] ScrollingViewBehavior_Params;
    public static final int ScrollingViewBehavior_Params_behavior_overlapTop = 0;
    public static final int[] SearchQueryView;
    public static final int SearchQueryView_clearDrawablePosition = 0;
    public static final int[] SearchView;
    public static final int SearchView_android_focusable = 0;
    public static final int SearchView_android_imeOptions = 3;
    public static final int SearchView_android_inputType = 2;
    public static final int SearchView_android_maxWidth = 1;
    public static final int SearchView_closeIcon = 8;
    public static final int SearchView_commitIcon = 13;
    public static final int SearchView_defaultQueryHint = 7;
    public static final int SearchView_goIcon = 9;
    public static final int SearchView_iconifiedByDefault = 5;
    public static final int SearchView_layout = 4;
    public static final int SearchView_queryBackground = 15;
    public static final int SearchView_queryHint = 6;
    public static final int SearchView_searchHintIcon = 11;
    public static final int SearchView_searchIcon = 10;
    public static final int SearchView_submitBackground = 16;
    public static final int SearchView_suggestionRowLayout = 14;
    public static final int SearchView_voiceIcon = 12;
    public static final int[] ShadowTextView;
    public static final int ShadowTextView_shadowColor = 0;
    public static final int ShadowTextView_shadowDx = 1;
    public static final int ShadowTextView_shadowDy = 2;
    public static final int ShadowTextView_shadowRadius = 3;
    public static final int[] SignInButton;
    public static final int SignInButton_buttonSize = 0;
    public static final int SignInButton_colorScheme = 1;
    public static final int SignInButton_scopeUris = 2;
    public static final int[] SlidingPanel;
    public static final int SlidingPanel_panelContentLayoutId = 1;
    public static final int SlidingPanel_panelHeaderLayoutId = 0;
    public static final int[] SlidingTabLayout;
    public static final int SlidingTabLayout_bottomBorderColor = 2;
    public static final int SlidingTabLayout_bottomBorderThickness = 1;
    public static final int SlidingTabLayout_selectedIndicatorColor = 4;
    public static final int SlidingTabLayout_selectedIndicatorThickness = 3;
    public static final int SlidingTabLayout_tabDividerColor = 5;
    public static final int SlidingTabLayout_titleOffset = 0;
    public static final int[] SnackbarLayout;
    public static final int SnackbarLayout_android_maxWidth = 0;
    public static final int SnackbarLayout_elevation = 1;
    public static final int SnackbarLayout_maxActionInlineWidth = 2;
    public static final int[] SocialBylineView;
    public static final int SocialBylineView_iconMargin = 4;
    public static final int SocialBylineView_labelColor = 0;
    public static final int SocialBylineView_labelSize = 1;
    public static final int SocialBylineView_minIconWidth = 2;
    public static final int SocialBylineView_socialContextPadding = 3;
    public static final int[] SocialProofView;
    public static final int SocialProofView_android_lineSpacingExtra = 0;
    public static final int SocialProofView_android_lineSpacingMultiplier = 1;
    public static final int SocialProofView_badgeSpacing = 2;
    public static final int SocialProofView_badgeTextSpacing = 4;
    public static final int SocialProofView_socialProofTextColor = 3;
    public static final int[] Spinner;
    public static final int Spinner_android_dropDownWidth = 3;
    public static final int Spinner_android_entries = 0;
    public static final int Spinner_android_popupBackground = 1;
    public static final int Spinner_android_prompt = 2;
    public static final int Spinner_popupTheme = 4;
    public static final int[] StyleableRadioButton;
    public static final int StyleableRadioButton_checkedIconColor = 2;
    public static final int StyleableRadioButton_checkedStyle = 1;
    public static final int StyleableRadioButton_normalStyle = 0;
    public static final int StyleableRadioButton_uncheckedIconColor = 3;
    public static final int[] SuggestionEditText;
    public static final int SuggestionEditText_autoRefresh = 5;
    public static final int SuggestionEditText_cursorBottomPadding = 4;
    public static final int SuggestionEditText_focusOnDismiss = 2;
    public static final int SuggestionEditText_lengthThreshold = 1;
    public static final int SuggestionEditText_removePastedStyles = 3;
    public static final int SuggestionEditText_stripHtml = 0;
    public static final int[] SwitchCompat;
    public static final int SwitchCompat_android_textOff = 1;
    public static final int SwitchCompat_android_textOn = 0;
    public static final int SwitchCompat_android_thumb = 2;
    public static final int SwitchCompat_showText = 9;
    public static final int SwitchCompat_splitTrack = 8;
    public static final int SwitchCompat_switchMinWidth = 6;
    public static final int SwitchCompat_switchPadding = 7;
    public static final int SwitchCompat_switchTextAppearance = 5;
    public static final int SwitchCompat_thumbTextPadding = 4;
    public static final int SwitchCompat_track = 3;
    public static final int[] TabItem;
    public static final int TabItem_android_icon = 0;
    public static final int TabItem_android_layout = 1;
    public static final int TabItem_android_text = 2;
    public static final int[] TabLayout;
    public static final int TabLayout_tabBackground = 3;
    public static final int TabLayout_tabContentStart = 2;
    public static final int TabLayout_tabGravity = 5;
    public static final int TabLayout_tabIndicatorColor = 0;
    public static final int TabLayout_tabIndicatorHeight = 1;
    public static final int TabLayout_tabMaxWidth = 7;
    public static final int TabLayout_tabMinWidth = 6;
    public static final int TabLayout_tabMode = 4;
    public static final int TabLayout_tabPadding = 15;
    public static final int TabLayout_tabPaddingBottom = 14;
    public static final int TabLayout_tabPaddingEnd = 13;
    public static final int TabLayout_tabPaddingStart = 11;
    public static final int TabLayout_tabPaddingTop = 12;
    public static final int TabLayout_tabSelectedTextColor = 10;
    public static final int TabLayout_tabTextAppearance = 8;
    public static final int TabLayout_tabTextColor = 9;
    public static final int[] TextAppearance;
    public static final int TextAppearance_android_shadowColor = 4;
    public static final int TextAppearance_android_shadowDx = 5;
    public static final int TextAppearance_android_shadowDy = 6;
    public static final int TextAppearance_android_shadowRadius = 7;
    public static final int TextAppearance_android_textColor = 3;
    public static final int TextAppearance_android_textSize = 0;
    public static final int TextAppearance_android_textStyle = 2;
    public static final int TextAppearance_android_typeface = 1;
    public static final int TextAppearance_textAllCaps = 8;
    public static final int[] TextContentView;
    public static final int TextContentView_android_lineSpacingExtra = 2;
    public static final int TextContentView_android_lineSpacingMultiplier = 3;
    public static final int TextContentView_android_maxLines = 0;
    public static final int TextContentView_android_minLines = 1;
    public static final int TextContentView_contentColor = 4;
    public static final int TextContentView_linkColor = 5;
    public static final int[] TextInputLayout;
    public static final int TextInputLayout_android_hint = 1;
    public static final int TextInputLayout_android_textColorHint = 0;
    public static final int TextInputLayout_counterEnabled = 6;
    public static final int TextInputLayout_counterMaxLength = 7;
    public static final int TextInputLayout_counterOverflowTextAppearance = 9;
    public static final int TextInputLayout_counterTextAppearance = 8;
    public static final int TextInputLayout_errorEnabled = 4;
    public static final int TextInputLayout_errorTextAppearance = 5;
    public static final int TextInputLayout_hintAnimationEnabled = 10;
    public static final int TextInputLayout_hintEnabled = 3;
    public static final int TextInputLayout_hintTextAppearance = 2;
    public static final int[] TextLayoutView;
    public static final int TextLayoutView_android_lineSpacingExtra = 3;
    public static final int TextLayoutView_android_lineSpacingMultiplier = 4;
    public static final int TextLayoutView_android_text = 2;
    public static final int TextLayoutView_android_textColor = 1;
    public static final int TextLayoutView_android_textSize = 0;
    public static final int[] TickMarksView;
    public static final int TickMarksView_android_textSize = 0;
    public static final int TickMarksView_tickMarkLabelMarginLeft = 3;
    public static final int TickMarksView_tickMarkLabelMarginTop = 4;
    public static final int TickMarksView_tickMarksMarkWidth = 2;
    public static final int TickMarksView_tickMarksMinGap = 1;
    public static final int[] TightTextView;
    public static final int TightTextView_horizontal_alignment = 1;
    public static final int TightTextView_text = 5;
    public static final int TightTextView_text_color = 4;
    public static final int TightTextView_text_face = 3;
    public static final int TightTextView_text_size = 2;
    public static final int TightTextView_vertical_alignment = 0;
    public static final int[] TintableImageView;
    public static final int TintableImageView_tintColorList = 0;
    public static final int[] ToggleTwitterButton;
    public static final int ToggleTwitterButton_initOn = 4;
    public static final int ToggleTwitterButton_shouldToggleOnClick = 3;
    public static final int ToggleTwitterButton_showIconOn = 2;
    public static final int ToggleTwitterButton_styleIdOff = 1;
    public static final int ToggleTwitterButton_styleIdOn = 0;
    public static final int[] ToolBar;
    public static final int[] ToolBarHomeView;
    public static final int ToolBarHomeView_allCaps = 9;
    public static final int ToolBarHomeView_iconVisibleWithUp = 10;
    public static final int ToolBarHomeView_numberBackground = 4;
    public static final int ToolBarHomeView_numberColor = 5;
    public static final int ToolBarHomeView_subtitleTextColor = 11;
    public static final int ToolBarHomeView_subtitleTextSize = 6;
    public static final int ToolBarHomeView_subtitleTextStyle = 3;
    public static final int ToolBarHomeView_textColor = 0;
    public static final int ToolBarHomeView_textSize = 1;
    public static final int ToolBarHomeView_titleTextStyle = 2;
    public static final int ToolBarHomeView_toolBarIconSpacing = 7;
    public static final int ToolBarHomeView_upIndicatorDescription = 8;
    public static final int[] ToolBarItem;
    public static final int[] ToolBarItemView;
    public static final int ToolBarItemView_badgeIndicatorStyle = 0;
    public static final int ToolBarItemView_textColor = 1;
    public static final int ToolBarItemView_textSize = 2;
    public static final int ToolBarItem_actionLayout = 10;
    public static final int ToolBarItem_alignLeft = 16;
    public static final int ToolBarItem_android_contentDescription = 5;
    public static final int ToolBarItem_android_enabled = 1;
    public static final int ToolBarItem_android_icon = 0;
    public static final int ToolBarItem_android_id = 2;
    public static final int ToolBarItem_android_showAsAction = 6;
    public static final int ToolBarItem_android_title = 4;
    public static final int ToolBarItem_android_visible = 3;
    public static final int ToolBarItem_checkIconAgainstColor = 19;
    public static final int ToolBarItem_component = 13;
    public static final int ToolBarItem_drawerIcon = 15;
    public static final int ToolBarItem_drawerTitle = 14;
    public static final int ToolBarItem_groupId = 12;
    public static final int ToolBarItem_maxIconSize = 17;
    public static final int ToolBarItem_order = 7;
    public static final int ToolBarItem_overflowIcon = 11;
    public static final int ToolBarItem_priority = 8;
    public static final int ToolBarItem_strokeAlpha = 18;
    public static final int ToolBarItem_strokeColor = 20;
    public static final int ToolBarItem_strokeWidth = 21;
    public static final int ToolBarItem_subtitle = 9;
    public static final int[] ToolBarLayout;
    public static final int ToolBarLayout_android_layout_gravity = 0;
    public static final int ToolBar_popupMenuXOffset = 0;
    public static final int ToolBar_toolBarCustomViewId = 11;
    public static final int ToolBar_toolBarDisplayOptions = 14;
    public static final int ToolBar_toolBarDrawerItemStyle = 1;
    public static final int ToolBar_toolBarHomeStyle = 2;
    public static final int ToolBar_toolBarIcon = 8;
    public static final int ToolBar_toolBarItemBackground = 5;
    public static final int ToolBar_toolBarItemPadding = 6;
    public static final int ToolBar_toolBarItemStyle = 3;
    public static final int ToolBar_toolBarOverflowContentDescription = 12;
    public static final int ToolBar_toolBarOverflowDrawable = 10;
    public static final int ToolBar_toolBarPaddingTop = 13;
    public static final int ToolBar_toolBarTheme = 4;
    public static final int ToolBar_toolBarTitle = 7;
    public static final int ToolBar_toolBarUpIndicator = 9;
    public static final int[] Toolbar;
    public static final int[] ToolbarWrapperLayout;
    public static final int ToolbarWrapperLayout_manualToolbarElevation = 1;
    public static final int ToolbarWrapperLayout_relayoutToolbar = 3;
    public static final int ToolbarWrapperLayout_shouldDrawManualShadow = 2;
    public static final int ToolbarWrapperLayout_toolBarId = 0;
    public static final int Toolbar_android_gravity = 0;
    public static final int Toolbar_android_minHeight = 1;
    public static final int Toolbar_collapseContentDescription = 19;
    public static final int Toolbar_collapseIcon = 18;
    public static final int Toolbar_contentInsetEnd = 6;
    public static final int Toolbar_contentInsetLeft = 7;
    public static final int Toolbar_contentInsetRight = 8;
    public static final int Toolbar_contentInsetStart = 5;
    public static final int Toolbar_logo = 4;
    public static final int Toolbar_logoDescription = 22;
    public static final int Toolbar_maxButtonHeight = 17;
    public static final int Toolbar_navigationContentDescription = 21;
    public static final int Toolbar_navigationIcon = 20;
    public static final int Toolbar_popupTheme = 9;
    public static final int Toolbar_subtitle = 3;
    public static final int Toolbar_subtitleTextAppearance = 11;
    public static final int Toolbar_subtitleTextColor = 24;
    public static final int Toolbar_title = 2;
    public static final int Toolbar_titleMarginBottom = 16;
    public static final int Toolbar_titleMarginEnd = 14;
    public static final int Toolbar_titleMarginStart = 13;
    public static final int Toolbar_titleMarginTop = 15;
    public static final int Toolbar_titleMargins = 12;
    public static final int Toolbar_titleTextAppearance = 10;
    public static final int Toolbar_titleTextColor = 23;
    public static final int[] TooltipView;
    public static final int TooltipView_arrowHeight = 6;
    public static final int TooltipView_arrowWidth = 5;
    public static final int TooltipView_cornerRadius = 0;
    public static final int TooltipView_screenEdgePadding = 7;
    public static final int TooltipView_textAppearance = 4;
    public static final int TooltipView_tooltipColor = 3;
    public static final int TooltipView_transitionAnimationDelayMs = 8;
    public static final int TooltipView_xOffset = 1;
    public static final int TooltipView_yOffset = 2;
    public static final int[] TouchForwardingFrameLayout;
    public static final int TouchForwardingFrameLayout_targetViewGroup = 0;
    public static final int[] TouchInterceptor;
    public static final int TouchInterceptor_dragBackground = 2;
    public static final int TouchInterceptor_expandedItemHeight = 1;
    public static final int TouchInterceptor_normalItemHeight = 0;
    public static final int[] TweetHeaderView;
    public static final int TweetHeaderView_android_lineSpacingExtra = 0;
    public static final int TweetHeaderView_android_lineSpacingMultiplier = 1;
    public static final int TweetHeaderView_headerIconSpacing = 6;
    public static final int TweetHeaderView_indicatorColor = 5;
    public static final int TweetHeaderView_nameColor = 2;
    public static final int TweetHeaderView_timestampColor = 4;
    public static final int TweetHeaderView_usernameColor = 3;
    public static final int[] TweetMediaView;
    public static final int TweetMediaView_audioBadgeDrawable = 6;
    public static final int TweetMediaView_cardBadgeSpacing = 12;
    public static final int TweetMediaView_cornerRadiusSize = 4;
    public static final int TweetMediaView_defaultDrawable = 0;
    public static final int TweetMediaView_dividerSize = 1;
    public static final int TweetMediaView_gifBadgeDrawable = 7;
    public static final int TweetMediaView_mediaBorderColor = 14;
    public static final int TweetMediaView_mediaBorderSize = 13;
    public static final int TweetMediaView_momentsBadgeDrawable = 10;
    public static final int TweetMediaView_multipleMediaBorderColor = 15;
    public static final int TweetMediaView_overlayDrawable = 2;
    public static final int TweetMediaView_playerOverlay = 3;
    public static final int TweetMediaView_progressBarSize = 5;
    public static final int TweetMediaView_snapreelBadgeDrawable = 8;
    public static final int TweetMediaView_stickersBadgeDrawable = 11;
    public static final int TweetMediaView_vineBadgeDrawable = 9;
    public static final int[] TweetPivotView;
    public static final int TweetPivotView_android_divider = 1;
    public static final int TweetPivotView_android_lineSpacingExtra = 2;
    public static final int TweetPivotView_android_lineSpacingMultiplier = 3;
    public static final int TweetPivotView_android_textSize = 0;
    public static final int TweetPivotView_tweetPivotHeightMargin = 4;
    public static final int TweetPivotView_tweetPivotTextColor = 5;
    public static final int[] TweetView;
    public static final int TweetView_alertDrawable = 0;
    public static final int TweetView_autoLink = 24;
    public static final int TweetView_badgeSpacing = 1;
    public static final int TweetView_bylineSize = 2;
    public static final int TweetView_contentSize = 3;
    public static final int TweetView_iconSpacing = 6;
    public static final int TweetView_inlineActionBarPaddingNormal = 28;
    public static final int TweetView_linkSelectedColor = 25;
    public static final int TweetView_mediaBottomMargin = 22;
    public static final int TweetView_mediaDivider = 23;
    public static final int TweetView_mediaIcon = 9;
    public static final int TweetView_mediaPlaceholderDrawable = 20;
    public static final int TweetView_mediaTagIcon = 27;
    public static final int TweetView_mediaTopMargin = 21;
    public static final int TweetView_noPressStateBackgroundDrawable = 8;
    public static final int TweetView_placeholderColor = 7;
    public static final int TweetView_playerIcon = 10;
    public static final int TweetView_politicalDrawable = 4;
    public static final int TweetView_previewFlags = 26;
    public static final int TweetView_profileImageHeight = 16;
    public static final int TweetView_profileImagePaddingLeft = 13;
    public static final int TweetView_profileImagePaddingRight = 14;
    public static final int TweetView_profileImageWidth = 15;
    public static final int TweetView_promotedDrawable = 5;
    public static final int TweetView_summaryIcon = 11;
    public static final int TweetView_translationIcon = 12;
    public static final int TweetView_tweetViewLayoutId = 29;
    public static final int TweetView_verticalConnector = 17;
    public static final int TweetView_verticalConnectorMargin = 19;
    public static final int TweetView_verticalConnectorWidth = 18;
    public static final int[] TwitterButton;
    public static final int TwitterButton_bounded = 17;
    public static final int TwitterButton_buttonStyle = 2;
    public static final int TwitterButton_cornerRadius = 0;
    public static final int TwitterButton_fillColor = 6;
    public static final int TwitterButton_fillPressedColor = 7;
    public static final int TwitterButton_iconAndLabelMargin = 13;
    public static final int TwitterButton_iconCanBeFlipped = 11;
    public static final int TwitterButton_iconColor = 8;
    public static final int TwitterButton_iconLayout = 19;
    public static final int TwitterButton_iconMargin = 12;
    public static final int TwitterButton_iconPressedColor = 9;
    public static final int TwitterButton_iconSize = 10;
    public static final int TwitterButton_knockout = 18;
    public static final int TwitterButton_labelColor = 1;
    public static final int TwitterButton_labelMargin = 14;
    public static final int TwitterButton_labelPressedColor = 5;
    public static final int TwitterButton_nodpiBaseIconName = 16;
    public static final int TwitterButton_strokeColor = 3;
    public static final int TwitterButton_strokePressedColor = 4;
    public static final int TwitterButton_strokeWidth = 15;
    public static final int[] TwitterEditText;
    public static final int TwitterEditText_characterCounterColor = 12;
    public static final int TwitterEditText_characterCounterMode = 13;
    public static final int TwitterEditText_helperMessage = 7;
    public static final int TwitterEditText_labelColor = 0;
    public static final int TwitterEditText_labelSize = 1;
    public static final int TwitterEditText_labelStyle = 3;
    public static final int TwitterEditText_labelText = 2;
    public static final int TwitterEditText_maxCharacterCount = 11;
    public static final int TwitterEditText_messageColor = 8;
    public static final int TwitterEditText_messageSize = 9;
    public static final int TwitterEditText_messageStyle = 10;
    public static final int TwitterEditText_statusIcon = 5;
    public static final int TwitterEditText_statusIconPosition = 6;
    public static final int TwitterEditText_underlineStyle = 4;
    public static final int[] TwitterIndeterminateProgressSpinner;
    public static final int TwitterIndeterminateProgressSpinner_logoSize = 0;
    public static final int TwitterIndeterminateProgressSpinner_ringSize = 1;
    public static final int TwitterIndeterminateProgressSpinner_ringThickness = 2;
    public static final int TwitterIndeterminateProgressSpinner_whiteForeground = 3;
    public static final int[] TwitterSelection;
    public static final int TwitterSelection_dialogTheme = 1;
    public static final int TwitterSelection_displayLayout = 4;
    public static final int TwitterSelection_dropDownAnchor = 5;
    public static final int TwitterSelection_dropDownHeight = 7;
    public static final int TwitterSelection_dropDownWidth = 6;
    public static final int TwitterSelection_listLayout = 0;
    public static final int TwitterSelection_selectionMode = 2;
    public static final int TwitterSelection_showPopupOnClick = 3;
    public static final int[] UnderlineDrawable;
    public static final int UnderlineDrawable_android_color = 0;
    public static final int UnderlineDrawable_android_left = 1;
    public static final int UnderlineDrawable_android_right = 2;
    public static final int[] UserForwardView;
    public static final int UserForwardView_android_divider = 0;
    public static final int[] UserImageView;
    public static final int UserImageView_imageCornerRadius = 1;
    public static final int UserImageView_roundingStrategy = 2;
    public static final int UserImageView_userImageSize = 0;
    public static final int[] UserSocialView;
    public static final int UserSocialView_bylineSize = 0;
    public static final int UserSocialView_contentSize = 1;
    public static final int[] UserView;
    public static final int UserView_actionButtonPadding = 2;
    public static final int UserView_actionButtonPaddingBottom = 6;
    public static final int UserView_actionButtonPaddingLeft = 3;
    public static final int UserView_actionButtonPaddingRight = 5;
    public static final int UserView_actionButtonPaddingTop = 4;
    public static final int UserView_politicalDrawable = 0;
    public static final int UserView_profileTextColor = 7;
    public static final int UserView_promotedDrawable = 1;
    public static final int[] VideoDurationView;
    public static final int VideoDurationView_time_format = 0;
    public static final int[] View;
    public static final int[] ViewBackgroundHelper;
    public static final int ViewBackgroundHelper_android_background = 0;
    public static final int ViewBackgroundHelper_backgroundTint = 1;
    public static final int ViewBackgroundHelper_backgroundTintMode = 2;
    public static final int[] ViewPagerScrollBar;
    public static final int ViewPagerScrollBar_tabDrawable = 0;
    public static final int ViewPagerScrollBar_tabMaxHeight = 1;
    public static final int[] ViewStates;
    public static final int ViewStates_state_blank = 2;
    public static final int ViewStates_state_error = 1;
    public static final int ViewStates_state_fault = 0;
    public static final int ViewStates_state_validated = 3;
    public static final int[] ViewStubCompat;
    public static final int ViewStubCompat_android_id = 0;
    public static final int ViewStubCompat_android_inflatedId = 2;
    public static final int ViewStubCompat_android_layout = 1;
    public static final int View_android_focusable = 1;
    public static final int View_android_theme = 0;
    public static final int View_paddingEnd = 3;
    public static final int View_paddingStart = 2;
    public static final int View_theme = 4;
    public static final int[] WhoToFollowUsersView;
    public static final int WhoToFollowUsersView_initial_user_count = 0;

    static {
        ActionBar = new int[]{bct.height, bct.title, bct.navigationMode, bct.displayOptions, bct.subtitle, bct.titleTextStyle, bct.subtitleTextStyle, bct.icon, bct.logo, bct.divider, bct.background, bct.backgroundStacked, bct.backgroundSplit, bct.customNavigationLayout, bct.homeLayout, bct.progressBarStyle, bct.indeterminateProgressStyle, bct.progressBarPadding, bct.itemPadding, bct.hideOnContentScroll, bct.contentInsetStart, bct.contentInsetEnd, bct.contentInsetLeft, bct.contentInsetRight, bct.elevation, bct.popupTheme, bct.homeAsUpIndicator};
        int[] iArr = new int[View_android_focusable];
        iArr[View_android_theme] = 16842931;
        ActionBarLayout = iArr;
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = 16843071;
        ActionMenuItemView = iArr;
        ActionMenuView = new int[View_android_theme];
        ActionMode = new int[]{bct.height, bct.titleTextStyle, bct.subtitleTextStyle, bct.background, bct.backgroundSplit, bct.closeItemLayout};
        ActionPromptView = new int[]{bct.actionPromptPointerHeight, bct.actionPromptBackgroundColor, bct.actionPromptPointerRadius};
        ActivityChooserView = new int[]{bct.initialActivityCount, bct.expandActivityOverflowButtonDrawable};
        AdsAttrs = new int[]{bct.adSize, bct.adSizes, bct.adUnitId};
        AlertDialog = new int[]{16842994, bct.buttonPanelSideLayout, bct.listLayout, bct.multiChoiceItemLayout, bct.singleChoiceItemLayout, bct.listItemLayout};
        AnimatedGifView = new int[]{bct.MinimumRepeatCount, bct.MinimumDurationMs, bct.GifBackgroundColor};
        AppBarLayout = new int[]{16842964, bct.elevation, bct.expanded};
        AppBarLayout_LayoutParams = new int[]{bct.layout_scrollFlags, bct.layout_scrollInterpolator};
        AppCompatImageView = new int[]{16843033, bct.srcCompat};
        AppCompatTextView = new int[]{16842804, bct.textAllCaps};
        AppCompatTheme = new int[]{16842839, 16842926, bct.windowActionBar, bct.windowNoTitle, bct.windowActionBarOverlay, bct.windowActionModeOverlay, bct.windowFixedWidthMajor, bct.windowFixedHeightMinor, bct.windowFixedWidthMinor, bct.windowFixedHeightMajor, bct.windowMinWidthMajor, bct.windowMinWidthMinor, bct.actionBarTabStyle, bct.actionBarTabBarStyle, bct.actionBarTabTextStyle, bct.actionOverflowButtonStyle, bct.actionOverflowMenuStyle, bct.actionBarPopupTheme, bct.actionBarStyle, bct.actionBarSplitStyle, bct.actionBarTheme, bct.actionBarWidgetTheme, bct.actionBarSize, bct.actionBarDivider, bct.actionBarItemBackground, bct.actionMenuTextAppearance, bct.actionMenuTextColor, bct.actionModeStyle, bct.actionModeCloseButtonStyle, bct.actionModeBackground, bct.actionModeSplitBackground, bct.actionModeCloseDrawable, bct.actionModeCutDrawable, bct.actionModeCopyDrawable, bct.actionModePasteDrawable, bct.actionModeSelectAllDrawable, bct.actionModeShareDrawable, bct.actionModeFindDrawable, bct.actionModeWebSearchDrawable, bct.actionModePopupWindowStyle, bct.textAppearanceLargePopupMenu, bct.textAppearanceSmallPopupMenu, bct.dialogTheme, bct.dialogPreferredPadding, bct.listDividerAlertDialog, bct.actionDropDownStyle, bct.dropdownListPreferredItemHeight, bct.spinnerDropDownItemStyle, bct.homeAsUpIndicator, bct.actionButtonStyle, bct.buttonBarStyle, bct.buttonBarButtonStyle, bct.selectableItemBackground, bct.selectableItemBackgroundBorderless, bct.borderlessButtonStyle, bct.dividerVertical, bct.dividerHorizontal, bct.activityChooserViewStyle, bct.toolbarStyle, bct.toolbarNavigationButtonStyle, bct.popupMenuStyle, bct.popupWindowStyle, bct.editTextColor, bct.editTextBackground, bct.imageButtonStyle, bct.textAppearanceSearchResultTitle, bct.textAppearanceSearchResultSubtitle, bct.textColorSearchUrl, bct.searchViewStyle, bct.listPreferredItemHeight, bct.listPreferredItemHeightSmall, bct.listPreferredItemHeightLarge, bct.listPreferredItemPaddingLeft, bct.listPreferredItemPaddingRight, bct.dropDownListViewStyle, bct.listPopupWindowStyle, bct.textAppearanceListItem, bct.textAppearanceListItemSmall, bct.panelBackground, bct.panelMenuListWidth, bct.panelMenuListTheme, bct.listChoiceBackgroundIndicator, bct.colorPrimary, bct.colorPrimaryDark, bct.colorAccent, bct.colorControlNormal, bct.colorControlActivated, bct.colorControlHighlight, bct.colorButtonNormal, bct.colorSwitchThumbNormal, bct.controlBackground, bct.alertDialogStyle, bct.alertDialogButtonGroupStyle, bct.alertDialogCenterButtons, bct.alertDialogTheme, bct.textColorAlertDialogListItem, bct.buttonBarPositiveButtonStyle, bct.buttonBarNegativeButtonStyle, bct.buttonBarNeutralButtonStyle, bct.autoCompleteTextViewStyle, bct.buttonStyle, bct.buttonStyleSmall, bct.checkboxStyle, bct.checkedTextViewStyle, bct.editTextStyle, bct.radioButtonStyle, bct.ratingBarStyle, bct.ratingBarStyleIndicator, bct.ratingBarStyleSmall, bct.seekBarStyle, bct.spinnerStyle, bct.switchStyle};
        AspectRatioFrameLayout = new int[]{bct.aspect_ratio, bct.min_aspect_ratio, bct.max_aspect_ratio, bct.max_width, bct.max_height, bct.scaleMode};
        BackgroundImageView = new int[]{bct.overlayDrawable, bct.crossfadeDuration, bct.filterMaxOpacity, bct.filterColor};
        BadgeIndicator = new int[]{bct.indicatorDrawable, bct.indicatorMarginBottom, bct.numberBackground, bct.numberColor, bct.numberTextSize, bct.numberMinWidth, bct.numberMinHeight, bct.circleDrawable, bct.circleMarginTop, bct.circleMarginRight, bct.badgeMode};
        BadgeView = new int[]{16842901, 16843287, 16843288, bct.badgeSpacing, bct.contentColor, bct.showBadge};
        BaseMediaImageView = new int[]{bct.defaultDrawable, bct.errorDrawable, bct.imageType, bct.updateOnResize, bct.scaleType};
        BottomSheetBehavior_Params = new int[]{bct.behavior_peekHeight, bct.behavior_hideable};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = bct.allowStacking;
        ButtonBarLayout = iArr;
        CardView = new int[]{bct.elementPressedColor, bct.imagePlaceholderColor, bct.playerOverlay};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = 16842931;
        CellLayout_Layout = iArr;
        ChannelView = new int[]{bct.ps__includeComposer, bct.ps__heartsMarginFactor};
        ClipRowView = new int[]{bct.insetPaddingStart, bct.insetWidth, bct.insetHeight, bct.insetDividerHeight, bct.insetDividerColor};
        CollapsingAppBarLayout_LayoutParams = new int[]{bct.layout_collapseMode, bct.layout_collapseParallaxMultiplier};
        CollapsingToolbarLayout = new int[]{bct.title, bct.expandedTitleMargin, bct.expandedTitleMarginStart, bct.expandedTitleMarginTop, bct.expandedTitleMarginEnd, bct.expandedTitleMarginBottom, bct.expandedTitleTextAppearance, bct.collapsedTitleTextAppearance, bct.contentScrim, bct.statusBarScrim, bct.toolbarId, bct.collapsedTitleGravity, bct.expandedTitleGravity, bct.titleEnabled};
        CompoundButton = new int[]{16843015, bct.buttonTint, bct.buttonTintMode};
        CompoundDrawableAnimButton = new int[]{bct.state_animate_to_checked, bct.state_animate_to_default, bct.transition_duration};
        CoordinatorLayout = new int[]{bct.keylines, bct.statusBarBackground};
        CoordinatorLayout_LayoutParams = new int[]{16842931, bct.layout_behavior, bct.layout_anchor, bct.layout_keyline, bct.layout_anchorGravity};
        CropContainerView = new int[]{bct.cropper_cropWidth, bct.cropper_cropAspectRatio, bct.cropper_cornerRadius, bct.cropper_strokeWidth, bct.cropper_strokeColor, bct.cropper_overlayColor};
        CroppableImageView = new int[]{bct.toolbarMargin, bct.cropRectPadding, bct.cropRectStrokeColor, bct.cropRectStrokeWidth, bct.cropShadowColor, bct.draggableCorners, bct.showGrid, bct.gridColor};
        DesignTheme = new int[]{bct.bottomSheetDialogTheme, bct.bottomSheetStyle, bct.textColorError};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = bct.dismissOverlayDrawable;
        DismissableOverlayImageView = iArr;
        DockLayout = new int[]{bct.topDockId, bct.bottomDockId, bct.turtle, bct.topPeek, bct.bottomPeek, bct.scrollDrive, bct.autoUnlock, bct.disableAccessibilityLockOverride};
        DrawerArrowToggle = new int[]{bct.color, bct.spinBars, bct.drawableSize, bct.gapBetweenBars, bct.arrowHeadLength, bct.arrowShaftLength, bct.barLength, bct.thickness};
        EditableMediaView = new int[]{bct.playerOverlay, bct.itemPadding, bct.animatedGifViewLayout, bct.layout};
        FadeInTextView = new int[]{16842901, 16842904, 16843160, bct.texts};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = bct.fixedSize;
        FixedSizeImageView = iArr;
        FloatingActionButton = new int[]{bct.elevation, bct.rippleColor, bct.fabSize, bct.pressedTranslationZ, bct.borderWidth, bct.useCompatPadding, bct.backgroundTint, bct.backgroundTintMode};
        FlowLayout = new int[]{bct.horizontalSpacing, bct.verticalSpacing};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = bct.ignoreParentPadding;
        FlowLayoutManagerLayout = iArr;
        ForegroundLinearLayout = new int[]{16843017, 16843264, bct.foregroundInsidePadding};
        GenericDraweeView = new int[]{bct.fadeDuration, bct.viewAspectRatio, bct.placeholderImage, bct.placeholderImageScaleType, bct.retryImage, bct.retryImageScaleType, bct.failureImage, bct.failureImageScaleType, bct.progressBarImage, bct.progressBarImageScaleType, bct.progressBarAutoRotateInterval, bct.actualImageScaleType, bct.backgroundImage, bct.overlayImage, bct.pressedStateOverlayImage, bct.roundAsCircle, bct.roundedCornerRadius, bct.roundTopLeft, bct.roundTopRight, bct.roundBottomRight, bct.roundBottomLeft, bct.roundWithOverlayColor, bct.roundingBorderWidth, bct.roundingBorderColor};
        GridLinesView = new int[]{bct.grid_line_width, bct.line_stroke_width, bct.number_of_horizontal_lines, bct.number_of_vertical_lines, bct.grid_line_color, bct.line_stroke_color};
        GroupedRowView = new int[]{bct.cardStyle, bct.groupStyle, bct.single, bct.hideDivider, bct.hideBorder, bct.borderColor, bct.borderHeight, bct.gapSize, bct.fillColor};
        HorizontalListView = new int[]{bct.listDivider, bct.dividerWidth, bct.edgePadding, bct.fillWidthHeightRatio, bct.scrollOffset, bct.scrollDrawable, bct.scrollHeight, bct.fillMode, bct.leftFadeInDrawable, bct.rightFadeInDrawable};
        InlineActionBar = new int[]{bct.displayBorder, bct.inlineActionBorderWidth};
        InlineActionTextStyle = new int[]{bct.textColor, bct.textBackground, bct.textFontSize, bct.textHorizontalPadding, bct.textVerticalPadding};
        InlineActionView = new int[]{bct.inlineActionDrawable, bct.iconPaddingNormal, bct.iconPaddingBadgeMode, bct.badgeMaskWidth, bct.badgeSidePadding, bct.inlineActionLabelMargin, bct.showLabel, bct.badgeTextStyle, bct.labelTextStyle};
        LinearLayoutCompat = new int[]{16842927, 16842948, 16843046, 16843047, 16843048, bct.divider, bct.measureWithLargestChild, bct.showDividers, bct.dividerPadding};
        LinearLayoutCompat_Layout = new int[]{16842931, 16842996, 16842997, 16843137};
        ListPopupWindow = new int[]{16843436, 16843437};
        LoadingImageView = new int[]{bct.imageAspectRatioAdjust, bct.imageAspectRatio, bct.circleCrop};
        MapAttrs = new int[]{bct.mapType, bct.cameraBearing, bct.cameraTargetLat, bct.cameraTargetLng, bct.cameraTilt, bct.cameraZoom, bct.liteMode, bct.uiCompass, bct.uiRotateGestures, bct.uiScrollGestures, bct.uiTiltGestures, bct.uiZoomControls, bct.uiZoomGestures, bct.useViewLifecycle, bct.zOrderOnTop, bct.uiMapToolbar, bct.ambientEnabled};
        MaskImageView = new int[]{bct.ps__cornerRadius, bct.ps__maskType};
        MediaImageView = new int[]{bct.fadeIn, bct.singleImageView, bct.scaleFactor, bct.loadingProgressBar};
        MenuGroup = new int[]{16842766, 16842960, 16843156, 16843230, 16843231, 16843232};
        MenuItem = new int[]{16842754, 16842766, 16842960, 16843014, 16843156, 16843230, 16843231, 16843233, 16843234, 16843235, 16843236, 16843237, 16843375, bct.showAsAction, bct.actionLayout, bct.actionViewClass, bct.actionProviderClass};
        MenuView = new int[]{16842926, 16843052, 16843053, 16843054, 16843055, 16843056, 16843057, bct.preserveIconSpacing};
        NavItemView = new int[]{bct.badgeIndicatorStyle, bct.selectedTextStyle, bct.textColor, bct.textSize, bct.textStyle, bct.displayMode, bct.unselectedIconTint};
        NavigationView = new int[]{16842964, 16842973, 16843039, bct.elevation, bct.menu, bct.itemIconTint, bct.itemTextColor, bct.itemBackground, bct.itemTextAppearance, bct.headerLayout};
        NotificationSocialProofStyle = new int[]{bct.eventTypeFollowDrawable, bct.eventTypeJoinedTwitterDrawable, bct.eventTypeFavoriteDrawable, bct.eventTypeFavoritedRetweetDrawable, bct.eventTypeFavoritedMentionDrawable, bct.eventTypeRetweetDrawable, bct.eventTypeRetweetedRetweetDrawable, bct.eventTypeRetweetedMentionDrawable, bct.eventTypeFavoritedMediaTagDrawable, bct.eventTypeRetweetedMediaTagDrawable};
        PageableListView = new int[]{bct.loadingHeaderLayout, bct.loadingHeaderDivider, bct.loadingFooterLayout, bct.defaultPosition};
        PillToggleButton = new int[]{bct.borderStrokeWidth, bct.unselectedBorderColor, bct.unselectedTextColor, bct.selectedBackgroundColor, bct.selectedTextColor, bct.checkDrawable, bct.plusDrawable};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = bct.ps__includeComposer;
        PlayerView = iArr;
        PopupEditText = new int[]{bct.popupMenuXOffset, bct.popupMenuYOffset, bct.showAsDropdown, bct.showFullScreen, bct.threshold, bct.showPopupOnInitialFocus, bct.stripHtml};
        PopupSuggestionEditText = new int[]{bct.popupMenuXOffset, bct.popupMenuYOffset, bct.showAsDropdown, bct.showFullScreen};
        PopupWindow = new int[]{16843126, bct.overlapAnchor};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = bct.state_above_anchor;
        PopupWindowBackgroundState = iArr;
        ProfileCardView = new int[]{bct.profileCardAvatarSize, bct.profileCardBottomPadding, bct.profileImageTopMarginRatio, bct.profileUserImageStrokeWidth, bct.profileDescriptionFontSize};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = 16843062;
        ProgressLayout = iArr;
        PromptView = new int[]{bct.titleText, bct.subtitleText, bct.buttonText, bct.showDismiss, bct.isHeader};
        PsImageView = new int[]{bct.ps__tint, bct.ps__toolTipOn, bct.ps__toolTipOff};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = bct.ps__halfHeight;
        PsLoading = iArr;
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = bct.ps__font;
        PsTextView = iArr;
        QuoteView = new int[]{bct.bylineColor, bct.bylineSize, bct.contentColor, bct.contentSize, bct.borderWidth, bct.borderColor, bct.interstitialTextSize, bct.interstitialTextColor, bct.interstitialBackgroundColor, bct.compactMediaWidth, bct.mediaDividerSize, bct.mediaPlaceholder, bct.quoteViewHeaderStyle, bct.quoteViewReplyContextStyle, bct.contentPaddingTop, bct.mediaTextGap, bct.borderCornerRadius, bct.sensitiveMediaCoverDrawable, bct.sensitiveMediaCoverSmallDrawable};
        RecyclerView = new int[]{16842948, bct.layoutManager, bct.spanCount, bct.reverseLayout, bct.stackFromEnd};
        RichImageView = new int[]{bct.cornerRadius, bct.overlayDrawable, bct.cornerRadiusTopLeft, bct.cornerRadiusTopRight, bct.cornerRadiusBottomLeft, bct.cornerRadiusBottomRight};
        RoundedGroupedRowView = new int[]{bct.cardStyle, bct.cornerRadius, bct.dividerColor, bct.groupStyle, bct.shadowColor, bct.shadowDx, bct.shadowDy, bct.shadowRadius, bct.single, bct.inset, bct.insetLeft, bct.insetTop, bct.insetRight, bct.insetBottom, bct.insetBottomFillColor, bct.dividerHeight, bct.strokeColor, bct.strokeWidth};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = bct.svg;
        SVGImageView = iArr;
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = bct.insetForeground;
        ScrimInsetsFrameLayout = iArr;
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = bct.behavior_overlapTop;
        ScrollingViewBehavior_Params = iArr;
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = bct.clearDrawablePosition;
        SearchQueryView = iArr;
        SearchView = new int[]{16842970, 16843039, 16843296, 16843364, bct.layout, bct.iconifiedByDefault, bct.queryHint, bct.defaultQueryHint, bct.closeIcon, bct.goIcon, bct.searchIcon, bct.searchHintIcon, bct.voiceIcon, bct.commitIcon, bct.suggestionRowLayout, bct.queryBackground, bct.submitBackground};
        ShadowTextView = new int[]{bct.shadowColor, bct.shadowDx, bct.shadowDy, bct.shadowRadius};
        SignInButton = new int[]{bct.buttonSize, bct.colorScheme, bct.scopeUris};
        SlidingPanel = new int[]{bct.panelHeaderLayoutId, bct.panelContentLayoutId};
        SlidingTabLayout = new int[]{bct.titleOffset, bct.bottomBorderThickness, bct.bottomBorderColor, bct.selectedIndicatorThickness, bct.selectedIndicatorColor, bct.tabDividerColor};
        SnackbarLayout = new int[]{16843039, bct.elevation, bct.maxActionInlineWidth};
        SocialBylineView = new int[]{bct.labelColor, bct.labelSize, bct.minIconWidth, bct.socialContextPadding, bct.iconMargin};
        SocialProofView = new int[]{16843287, 16843288, bct.badgeSpacing, bct.socialProofTextColor, bct.badgeTextSpacing};
        Spinner = new int[]{16842930, 16843126, 16843131, 16843362, bct.popupTheme};
        StyleableRadioButton = new int[]{bct.normalStyle, bct.checkedStyle, bct.checkedIconColor, bct.uncheckedIconColor};
        SuggestionEditText = new int[]{bct.stripHtml, bct.lengthThreshold, bct.focusOnDismiss, bct.removePastedStyles, bct.cursorBottomPadding, bct.autoRefresh};
        SwitchCompat = new int[]{16843044, 16843045, 16843074, bct.track, bct.thumbTextPadding, bct.switchTextAppearance, bct.switchMinWidth, bct.switchPadding, bct.splitTrack, bct.showText};
        TabItem = new int[]{16842754, 16842994, 16843087};
        TabLayout = new int[]{bct.tabIndicatorColor, bct.tabIndicatorHeight, bct.tabContentStart, bct.tabBackground, bct.tabMode, bct.tabGravity, bct.tabMinWidth, bct.tabMaxWidth, bct.tabTextAppearance, bct.tabTextColor, bct.tabSelectedTextColor, bct.tabPaddingStart, bct.tabPaddingTop, bct.tabPaddingEnd, bct.tabPaddingBottom, bct.tabPadding};
        TextAppearance = new int[]{16842901, 16842902, 16842903, 16842904, 16843105, 16843106, 16843107, 16843108, bct.textAllCaps};
        TextContentView = new int[]{16843091, 16843094, 16843287, 16843288, bct.contentColor, bct.linkColor};
        TextInputLayout = new int[]{16842906, 16843088, bct.hintTextAppearance, bct.hintEnabled, bct.errorEnabled, bct.errorTextAppearance, bct.counterEnabled, bct.counterMaxLength, bct.counterTextAppearance, bct.counterOverflowTextAppearance, bct.hintAnimationEnabled};
        TextLayoutView = new int[]{16842901, 16842904, 16843087, 16843287, 16843288};
        TickMarksView = new int[]{16842901, bct.tickMarksMinGap, bct.tickMarksMarkWidth, bct.tickMarkLabelMarginLeft, bct.tickMarkLabelMarginTop};
        TightTextView = new int[]{bct.vertical_alignment, bct.horizontal_alignment, bct.text_size, bct.text_face, bct.text_color, bct.text};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = bct.tintColorList;
        TintableImageView = iArr;
        ToggleTwitterButton = new int[]{bct.styleIdOn, bct.styleIdOff, bct.showIconOn, bct.shouldToggleOnClick, bct.initOn};
        ToolBar = new int[]{bct.popupMenuXOffset, bct.toolBarDrawerItemStyle, bct.toolBarHomeStyle, bct.toolBarItemStyle, bct.toolBarTheme, bct.toolBarItemBackground, bct.toolBarItemPadding, bct.toolBarTitle, bct.toolBarIcon, bct.toolBarUpIndicator, bct.toolBarOverflowDrawable, bct.toolBarCustomViewId, bct.toolBarOverflowContentDescription, bct.toolBarPaddingTop, bct.toolBarDisplayOptions};
        ToolBarHomeView = new int[]{bct.textColor, bct.textSize, bct.titleTextStyle, bct.subtitleTextStyle, bct.numberBackground, bct.numberColor, bct.subtitleTextSize, bct.toolBarIconSpacing, bct.upIndicatorDescription, bct.allCaps, bct.iconVisibleWithUp, bct.subtitleTextColor};
        ToolBarItem = new int[]{16842754, 16842766, 16842960, 16843156, 16843233, 16843379, 16843481, bct.order, bct.priority, bct.subtitle, bct.actionLayout, bct.overflowIcon, bct.groupId, bct.component, bct.drawerTitle, bct.drawerIcon, bct.alignLeft, bct.maxIconSize, bct.strokeAlpha, bct.checkIconAgainstColor, bct.strokeColor, bct.strokeWidth};
        ToolBarItemView = new int[]{bct.badgeIndicatorStyle, bct.textColor, bct.textSize};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = 16842931;
        ToolBarLayout = iArr;
        Toolbar = new int[]{16842927, 16843072, bct.title, bct.subtitle, bct.logo, bct.contentInsetStart, bct.contentInsetEnd, bct.contentInsetLeft, bct.contentInsetRight, bct.popupTheme, bct.titleTextAppearance, bct.subtitleTextAppearance, bct.titleMargins, bct.titleMarginStart, bct.titleMarginEnd, bct.titleMarginTop, bct.titleMarginBottom, bct.maxButtonHeight, bct.collapseIcon, bct.collapseContentDescription, bct.navigationIcon, bct.navigationContentDescription, bct.logoDescription, bct.titleTextColor, bct.subtitleTextColor};
        ToolbarWrapperLayout = new int[]{bct.toolBarId, bct.manualToolbarElevation, bct.shouldDrawManualShadow, bct.relayoutToolbar};
        TooltipView = new int[]{bct.cornerRadius, bct.xOffset, bct.yOffset, bct.tooltipColor, bct.textAppearance, bct.arrowWidth, bct.arrowHeight, bct.screenEdgePadding, bct.transitionAnimationDelayMs};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = bct.targetViewGroup;
        TouchForwardingFrameLayout = iArr;
        TouchInterceptor = new int[]{bct.normalItemHeight, bct.expandedItemHeight, bct.dragBackground};
        TweetHeaderView = new int[]{16843287, 16843288, bct.nameColor, bct.usernameColor, bct.timestampColor, bct.indicatorColor, bct.headerIconSpacing};
        TweetMediaView = new int[]{bct.defaultDrawable, bct.dividerSize, bct.overlayDrawable, bct.playerOverlay, bct.cornerRadiusSize, bct.progressBarSize, bct.audioBadgeDrawable, bct.gifBadgeDrawable, bct.snapreelBadgeDrawable, bct.vineBadgeDrawable, bct.momentsBadgeDrawable, bct.stickersBadgeDrawable, bct.cardBadgeSpacing, bct.mediaBorderSize, bct.mediaBorderColor, bct.multipleMediaBorderColor};
        TweetPivotView = new int[]{16842901, 16843049, 16843287, 16843288, bct.tweetPivotHeightMargin, bct.tweetPivotTextColor};
        TweetView = new int[]{bct.alertDrawable, bct.badgeSpacing, bct.bylineSize, bct.contentSize, bct.politicalDrawable, bct.promotedDrawable, bct.iconSpacing, bct.placeholderColor, bct.noPressStateBackgroundDrawable, bct.mediaIcon, bct.playerIcon, bct.summaryIcon, bct.translationIcon, bct.profileImagePaddingLeft, bct.profileImagePaddingRight, bct.profileImageWidth, bct.profileImageHeight, bct.verticalConnector, bct.verticalConnectorWidth, bct.verticalConnectorMargin, bct.mediaPlaceholderDrawable, bct.mediaTopMargin, bct.mediaBottomMargin, bct.mediaDivider, bct.autoLink, bct.linkSelectedColor, bct.previewFlags, bct.mediaTagIcon, bct.inlineActionBarPaddingNormal, bct.tweetViewLayoutId};
        TwitterButton = new int[]{bct.cornerRadius, bct.labelColor, bct.buttonStyle, bct.strokeColor, bct.strokePressedColor, bct.labelPressedColor, bct.fillColor, bct.fillPressedColor, bct.iconColor, bct.iconPressedColor, bct.iconSize, bct.iconCanBeFlipped, bct.iconMargin, bct.iconAndLabelMargin, bct.labelMargin, bct.strokeWidth, bct.nodpiBaseIconName, bct.bounded, bct.knockout, bct.iconLayout};
        TwitterEditText = new int[]{bct.labelColor, bct.labelSize, bct.labelText, bct.labelStyle, bct.underlineStyle, bct.statusIcon, bct.statusIconPosition, bct.helperMessage, bct.messageColor, bct.messageSize, bct.messageStyle, bct.maxCharacterCount, bct.characterCounterColor, bct.characterCounterMode};
        TwitterIndeterminateProgressSpinner = new int[]{bct.logoSize, bct.ringSize, bct.ringThickness, bct.whiteForeground};
        TwitterSelection = new int[]{bct.listLayout, bct.dialogTheme, bct.selectionMode, bct.showPopupOnClick, bct.displayLayout, bct.dropDownAnchor, bct.dropDownWidth, bct.dropDownHeight};
        UnderlineDrawable = new int[]{16843173, 16843181, 16843183};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = 16843049;
        UserForwardView = iArr;
        UserImageView = new int[]{bct.userImageSize, bct.imageCornerRadius, bct.roundingStrategy};
        UserSocialView = new int[]{bct.bylineSize, bct.contentSize};
        UserView = new int[]{bct.politicalDrawable, bct.promotedDrawable, bct.actionButtonPadding, bct.actionButtonPaddingLeft, bct.actionButtonPaddingTop, bct.actionButtonPaddingRight, bct.actionButtonPaddingBottom, bct.profileTextColor};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = bct.time_format;
        VideoDurationView = iArr;
        View = new int[]{16842752, 16842970, bct.paddingStart, bct.paddingEnd, bct.theme};
        ViewBackgroundHelper = new int[]{16842964, bct.backgroundTint, bct.backgroundTintMode};
        ViewPagerScrollBar = new int[]{bct.tabDrawable, bct.tabMaxHeight};
        ViewStates = new int[]{bct.state_fault, bct.state_error, bct.state_blank, bct.state_validated};
        ViewStubCompat = new int[]{16842960, 16842994, 16842995};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = bct.initial_user_count;
        WhoToFollowUsersView = iArr;
    }
}
