package defpackage;

/* compiled from: Twttr */
/* renamed from: ccu */
public final class ccu {
    public static final int A;
    public static final int B;
    public static final int C;
    public static final int D;
    public static final int E;
    public static final int F;
    public static final int G;
    public static final String[] a;
    public static final int b;
    public static final int c;
    public static final int d;
    public static final int e;
    public static final int f;
    public static final int g;
    public static final int h;
    public static final int i;
    public static final int j;
    public static final int k;
    public static final int l;
    public static final int m;
    public static final int n;
    public static final int o;
    public static final int p;
    public static final int q;
    public static final int r;
    public static final int s;
    public static final int t;
    public static final int u;
    public static final int v;
    public static final int w;
    public static final int x;
    public static final int y;
    public static final int z;

    static {
        b = cdg.c.length;
        c = b + 1;
        d = b + 2;
        e = b + 3;
        f = b + 4;
        g = b + 5;
        h = b + 6;
        i = b + 7;
        j = b + 8;
        k = b + 9;
        l = b + 10;
        m = b + 11;
        n = b + 12;
        o = b + 13;
        p = b + 14;
        q = b + 15;
        r = b + 16;
        s = b + 17;
        t = b + 18;
        u = b + 19;
        v = b + 20;
        w = b + 21;
        x = b + 22;
        y = b + 23;
        z = b + 24;
        A = b + 25;
        B = b + 26;
        C = b + 27;
        D = b + 28;
        E = b + 29;
        F = b + 30;
        G = b + 31;
        a = new String[(cdg.c.length + 32)];
        System.arraycopy(cdg.c, 0, a, 0, cdg.c.length);
        a[b] = "search_id";
        a[c] = "s_type";
        a[d] = "type_id";
        a[e] = "related_data";
        a[f] = "u_users_user_id";
        a[g] = "u_users_username";
        a[h] = "u_users_name";
        a[i] = "u_users_image_url";
        a[j] = "u_users_user_flags";
        a[k] = "u_users_friendship";
        a[l] = "u_user_groups_pc";
        a[m] = "u_user_metadata_soc_type";
        a[n] = "u_user_metadata_soc_name";
        a[o] = "u_user_metadata_user_title";
        a[p] = "u_users_description";
        a[q] = "u_users_description_entities";
        a[r] = "ev_id";
        a[s] = "ev_type";
        a[t] = "ev_query";
        a[u] = "ev_title";
        a[v] = "ev_subtitle";
        a[w] = "ev_seed_hashtag";
        a[x] = "ev_view_url";
        a[y] = "ev_status";
        a[z] = "ev_image_url";
        a[A] = "ev_explanation";
        a[B] = "ev_tweet_count";
        a[C] = "ev_start_time";
        a[D] = "ev_content";
        a[E] = "status_metadata_reason_text";
        a[F] = "status_metadata_reason_icon_type";
        a[G] = "card_state_card_state";
    }
}
