package defpackage;

/* compiled from: Twttr */
/* renamed from: cdb */
public final class cdb {
    public static final int A;
    public static final int B;
    public static final int C;
    public static final int D;
    public static final int E;
    public static final int F;
    public static final int G;
    public static final int H;
    public static final int I;
    public static final String[] a;
    public static final int b;
    public static final int c;
    public static final int d;
    public static final int e;
    public static final int f;
    public static final int g;
    public static final int h;
    public static final int i;
    public static final int j;
    public static final int k;
    public static final int l;
    public static final int m;
    public static final int n;
    public static final int o;
    public static final int p;
    public static final int q;
    public static final int r;
    public static final int s;
    public static final int t;
    public static final int u;
    public static final int v;
    public static final int w;
    public static final int x;
    public static final int y;
    public static final int z;

    static {
        b = cdg.a.length;
        c = b + 1;
        d = b + 2;
        e = b + 3;
        f = b + 4;
        g = b + 5;
        h = b + 6;
        i = b + 7;
        j = b + 8;
        k = b + 9;
        l = b + 10;
        m = b + 11;
        n = b + 12;
        o = b + 13;
        p = b + 14;
        q = b + 15;
        r = b + 16;
        s = b + 17;
        t = b + 18;
        u = b + 19;
        v = b + 20;
        w = b + 21;
        x = b + 22;
        y = b + 23;
        z = b + 24;
        A = b + 25;
        B = b + 26;
        C = b + 27;
        D = b + 28;
        E = b + 29;
        F = b + 30;
        G = b + 31;
        H = b + 32;
        I = b + 33;
        a = new String[(cdg.a.length + 34)];
        System.arraycopy(cdg.a, 0, a, 0, cdg.a.length);
        a[b] = "u_users_user_id";
        a[c] = "u_users_username";
        a[d] = "u_users_name";
        a[e] = "u_users_username";
        a[f] = "u_users_image_url";
        a[g] = "u_users_header_url";
        a[h] = "u_users_user_flags";
        a[i] = "u_users_description";
        a[j] = "u_users_description_entities";
        a[k] = "u_users_location";
        a[l] = "u_users_web_url";
        a[m] = "u_users_url_entities";
        a[n] = "u_users_friendship";
        a[o] = "u_users_followers";
        a[p] = "u_users_profile_created";
        a[q] = "u_user_groups_pc";
        a[r] = "story_id";
        a[s] = "story_order";
        a[t] = "story_type";
        a[u] = "story_proof_type";
        a[v] = "story_proof_addl_count";
        a[w] = "story_meta_title";
        a[x] = "story_meta_subtitle";
        a[y] = "story_meta_query";
        a[z] = "story_meta_header_img_url";
        a[A] = "story_source";
        a[B] = "story_impression_info";
        a[C] = "data_type";
        a[D] = "story_is_read";
        a[E] = "story_tag";
        a[F] = "u_user_metadata_token";
        a[G] = "u_users_friends";
        a[H] = "u_users_link_color";
        a[I] = "u_users_structured_location";
    }
}
