package defpackage;

/* compiled from: Twttr */
/* renamed from: cdc */
public final class cdc {
    public static final int A;
    public static final int B;
    public static final int C;
    public static final int D;
    public static final int E;
    public static final int F;
    public static final int G;
    public static final int H;
    public static final int I;
    public static final int J;
    public static final int K;
    public static final int L;
    public static final int M;
    public static final int N;
    public static final int O;
    public static final int P;
    public static final int Q;
    public static final int R;
    public static final int S;
    public static final int T;
    public static final int U;
    public static final int V;
    public static final int W;
    public static final int X;
    public static final int Y;
    public static final int Z;
    public static final String[] a;
    public static final int aa;
    public static final int ab;
    public static final int ac;
    public static final int ad;
    public static final int ae;
    public static final int af;
    public static final int ag;
    public static final int ah;
    public static final int ai;
    public static final int aj;
    public static final int ak;
    public static final int al;
    public static final int am;
    public static final int an;
    public static final int ao;
    public static final int b;
    public static final int c;
    public static final int d;
    public static final int e;
    public static final int f;
    public static final int g;
    public static final int h;
    public static final int i;
    public static final int j;
    public static final int k;
    public static final int l;
    public static final int m;
    public static final int n;
    public static final int o;
    public static final int p;
    public static final int q;
    public static final int r;
    public static final int s;
    public static final int t;
    public static final int u;
    public static final int v;
    public static final int w;
    public static final int x;
    public static final int y;
    public static final int z;

    static {
        b = cdg.a.length;
        c = b + 1;
        d = b + 2;
        e = b + 3;
        f = b + 4;
        g = b + 5;
        h = b + 6;
        i = b + 7;
        j = b + 8;
        k = b + 9;
        l = b + 10;
        m = b + 11;
        n = b + 12;
        o = b + 13;
        p = b + 14;
        q = b + 15;
        r = b + 16;
        s = b + 17;
        t = b + 18;
        u = b + 19;
        v = b + 20;
        w = b + 21;
        x = b + 22;
        y = b + 23;
        z = b + 24;
        A = b + 25;
        B = b + 26;
        C = b + 27;
        D = b + 28;
        E = b + 29;
        F = b + 30;
        G = b + 31;
        H = b + 32;
        I = b + 33;
        J = b + 34;
        K = b + 35;
        L = b + 36;
        M = b + 37;
        N = b + 38;
        O = b + 39;
        P = b + 40;
        Q = b + 41;
        R = b + 42;
        S = b + 43;
        T = b + 44;
        U = b + 45;
        V = b + 46;
        W = b + 47;
        X = b + 48;
        Y = b + 49;
        Z = b + 50;
        aa = b + 51;
        ab = b + 52;
        ac = b + 53;
        ad = b + 54;
        ae = b + 55;
        af = b + 56;
        ag = b + 57;
        ah = b + 58;
        ai = b + 59;
        aj = b + 60;
        ak = b + 61;
        al = b + 62;
        am = b + 63;
        an = b + 64;
        ao = b + 65;
        a = new String[(cdg.a.length + 66)];
        System.arraycopy(cdg.a, 0, a, 0, cdg.a.length);
        a[b] = "_id";
        a[c] = "timeline_entity_id";
        a[d] = "timeline_entity_type";
        a[e] = "timeline_data_type";
        a[f] = "timeline_data";
        a[g] = "timeline_flags";
        a[h] = "timeline_sort_index";
        a[i] = "timeline_updated_at";
        a[j] = "timeline_is_read";
        a[k] = "timeline_scribe_content";
        a[l] = "status_metadata_soc_type";
        a[m] = "status_metadata_soc_name";
        a[n] = "status_metadata_soc_second_name";
        a[o] = "status_metadata_soc_fav_count";
        a[p] = "status_metadata_soc_rt_count";
        a[q] = "status_metadata_soc_others_count";
        a[r] = "ev_id";
        a[s] = "ev_type";
        a[t] = "ev_query";
        a[u] = "ev_title";
        a[v] = "ev_subtitle";
        a[w] = "ev_view_url";
        a[x] = "ev_status";
        a[y] = "ev_image_url";
        a[z] = "ev_explanation";
        a[A] = "ev_tweet_count";
        a[B] = "ev_pc";
        a[C] = "ev_content";
        a[D] = "ev_seed_hashtag";
        a[E] = "ev_start_time";
        a[F] = "timeline_timeline_group_id";
        a[G] = "timeline_timeline_scribe_group_id";
        a[H] = "wtf_user_id";
        a[I] = "wtf_name";
        a[J] = "wtf_username";
        a[K] = "wtf_image_url";
        a[L] = "wtf_friendship";
        a[M] = "wtf_header_url";
        a[N] = "wtf_description";
        a[O] = "wtf_link_color";
        a[P] = "wtf_user_flags";
        a[Q] = "wtf_description_entities";
        a[R] = "timeline_timeline_moment_info";
        a[S] = "p_id";
        a[T] = "p_format";
        a[U] = "p_template";
        a[V] = "p_header_text";
        a[W] = "p_body_text";
        a[X] = "p_primary_action_text";
        a[Y] = "p_primary_action_url";
        a[Z] = "p_primary_action_dismiss";
        a[aa] = "p_secondary_action_text";
        a[ab] = "p_secondary_action_url";
        a[ac] = "p_secondary_action_dismiss";
        a[ad] = "p_icon";
        a[ae] = "p_background_image_url";
        a[af] = "p_persistence";
        a[ag] = "p_entities";
        a[ah] = "p_header_entities";
        a[ai] = "p_status_id";
        a[aj] = "p_insertion_index";
        a[ak] = "p_trigger";
        a[al] = "p_dismissible";
        a[am] = "timeline_dismissed";
        a[an] = "timeline_dismiss_actions";
        a[ao] = "timeline_pinned_header_state";
        a[16] = "timeline_is_last";
        a[30] = "timeline_is_read";
    }
}
