package defpackage;

/* compiled from: Twttr */
/* renamed from: cse */
public final class cse {
    public static final int[] ActionBar;
    public static final int[] ActionBarLayout;
    public static final int ActionBarLayout_android_layout_gravity = 0;
    public static final int ActionBar_background = 10;
    public static final int ActionBar_backgroundSplit = 12;
    public static final int ActionBar_backgroundStacked = 11;
    public static final int ActionBar_contentInsetEnd = 21;
    public static final int ActionBar_contentInsetLeft = 22;
    public static final int ActionBar_contentInsetRight = 23;
    public static final int ActionBar_contentInsetStart = 20;
    public static final int ActionBar_customNavigationLayout = 13;
    public static final int ActionBar_displayOptions = 3;
    public static final int ActionBar_divider = 9;
    public static final int ActionBar_elevation = 24;
    public static final int ActionBar_height = 0;
    public static final int ActionBar_hideOnContentScroll = 19;
    public static final int ActionBar_homeAsUpIndicator = 26;
    public static final int ActionBar_homeLayout = 14;
    public static final int ActionBar_icon = 7;
    public static final int ActionBar_indeterminateProgressStyle = 16;
    public static final int ActionBar_itemPadding = 18;
    public static final int ActionBar_logo = 8;
    public static final int ActionBar_navigationMode = 2;
    public static final int ActionBar_popupTheme = 25;
    public static final int ActionBar_progressBarPadding = 17;
    public static final int ActionBar_progressBarStyle = 15;
    public static final int ActionBar_subtitle = 4;
    public static final int ActionBar_subtitleTextStyle = 6;
    public static final int ActionBar_title = 1;
    public static final int ActionBar_titleTextStyle = 5;
    public static final int[] ActionMenuItemView;
    public static final int ActionMenuItemView_android_minWidth = 0;
    public static final int[] ActionMenuView;
    public static final int[] ActionMode;
    public static final int ActionMode_background = 3;
    public static final int ActionMode_backgroundSplit = 4;
    public static final int ActionMode_closeItemLayout = 5;
    public static final int ActionMode_height = 0;
    public static final int ActionMode_subtitleTextStyle = 2;
    public static final int ActionMode_titleTextStyle = 1;
    public static final int[] ActivityChooserView;
    public static final int ActivityChooserView_expandActivityOverflowButtonDrawable = 1;
    public static final int ActivityChooserView_initialActivityCount = 0;
    public static final int[] AlertDialog;
    public static final int AlertDialog_android_layout = 0;
    public static final int AlertDialog_buttonPanelSideLayout = 1;
    public static final int AlertDialog_listItemLayout = 5;
    public static final int AlertDialog_listLayout = 2;
    public static final int AlertDialog_multiChoiceItemLayout = 3;
    public static final int AlertDialog_singleChoiceItemLayout = 4;
    public static final int[] AppBarLayout;
    public static final int[] AppBarLayout_LayoutParams;
    public static final int AppBarLayout_LayoutParams_layout_scrollFlags = 0;
    public static final int AppBarLayout_LayoutParams_layout_scrollInterpolator = 1;
    public static final int AppBarLayout_android_background = 0;
    public static final int AppBarLayout_elevation = 1;
    public static final int AppBarLayout_expanded = 2;
    public static final int[] AppCompatImageView;
    public static final int AppCompatImageView_android_src = 0;
    public static final int AppCompatImageView_srcCompat = 1;
    public static final int[] AppCompatTextView;
    public static final int AppCompatTextView_android_textAppearance = 0;
    public static final int AppCompatTextView_textAllCaps = 1;
    public static final int[] AppCompatTheme;
    public static final int AppCompatTheme_actionBarDivider = 23;
    public static final int AppCompatTheme_actionBarItemBackground = 24;
    public static final int AppCompatTheme_actionBarPopupTheme = 17;
    public static final int AppCompatTheme_actionBarSize = 22;
    public static final int AppCompatTheme_actionBarSplitStyle = 19;
    public static final int AppCompatTheme_actionBarStyle = 18;
    public static final int AppCompatTheme_actionBarTabBarStyle = 13;
    public static final int AppCompatTheme_actionBarTabStyle = 12;
    public static final int AppCompatTheme_actionBarTabTextStyle = 14;
    public static final int AppCompatTheme_actionBarTheme = 20;
    public static final int AppCompatTheme_actionBarWidgetTheme = 21;
    public static final int AppCompatTheme_actionButtonStyle = 49;
    public static final int AppCompatTheme_actionDropDownStyle = 45;
    public static final int AppCompatTheme_actionMenuTextAppearance = 25;
    public static final int AppCompatTheme_actionMenuTextColor = 26;
    public static final int AppCompatTheme_actionModeBackground = 29;
    public static final int AppCompatTheme_actionModeCloseButtonStyle = 28;
    public static final int AppCompatTheme_actionModeCloseDrawable = 31;
    public static final int AppCompatTheme_actionModeCopyDrawable = 33;
    public static final int AppCompatTheme_actionModeCutDrawable = 32;
    public static final int AppCompatTheme_actionModeFindDrawable = 37;
    public static final int AppCompatTheme_actionModePasteDrawable = 34;
    public static final int AppCompatTheme_actionModePopupWindowStyle = 39;
    public static final int AppCompatTheme_actionModeSelectAllDrawable = 35;
    public static final int AppCompatTheme_actionModeShareDrawable = 36;
    public static final int AppCompatTheme_actionModeSplitBackground = 30;
    public static final int AppCompatTheme_actionModeStyle = 27;
    public static final int AppCompatTheme_actionModeWebSearchDrawable = 38;
    public static final int AppCompatTheme_actionOverflowButtonStyle = 15;
    public static final int AppCompatTheme_actionOverflowMenuStyle = 16;
    public static final int AppCompatTheme_activityChooserViewStyle = 57;
    public static final int AppCompatTheme_alertDialogButtonGroupStyle = 92;
    public static final int AppCompatTheme_alertDialogCenterButtons = 93;
    public static final int AppCompatTheme_alertDialogStyle = 91;
    public static final int AppCompatTheme_alertDialogTheme = 94;
    public static final int AppCompatTheme_android_windowAnimationStyle = 1;
    public static final int AppCompatTheme_android_windowIsFloating = 0;
    public static final int AppCompatTheme_autoCompleteTextViewStyle = 99;
    public static final int AppCompatTheme_borderlessButtonStyle = 54;
    public static final int AppCompatTheme_buttonBarButtonStyle = 51;
    public static final int AppCompatTheme_buttonBarNegativeButtonStyle = 97;
    public static final int AppCompatTheme_buttonBarNeutralButtonStyle = 98;
    public static final int AppCompatTheme_buttonBarPositiveButtonStyle = 96;
    public static final int AppCompatTheme_buttonBarStyle = 50;
    public static final int AppCompatTheme_buttonStyle = 100;
    public static final int AppCompatTheme_buttonStyleSmall = 101;
    public static final int AppCompatTheme_checkboxStyle = 102;
    public static final int AppCompatTheme_checkedTextViewStyle = 103;
    public static final int AppCompatTheme_colorAccent = 84;
    public static final int AppCompatTheme_colorButtonNormal = 88;
    public static final int AppCompatTheme_colorControlActivated = 86;
    public static final int AppCompatTheme_colorControlHighlight = 87;
    public static final int AppCompatTheme_colorControlNormal = 85;
    public static final int AppCompatTheme_colorPrimary = 82;
    public static final int AppCompatTheme_colorPrimaryDark = 83;
    public static final int AppCompatTheme_colorSwitchThumbNormal = 89;
    public static final int AppCompatTheme_controlBackground = 90;
    public static final int AppCompatTheme_dialogPreferredPadding = 43;
    public static final int AppCompatTheme_dialogTheme = 42;
    public static final int AppCompatTheme_dividerHorizontal = 56;
    public static final int AppCompatTheme_dividerVertical = 55;
    public static final int AppCompatTheme_dropDownListViewStyle = 74;
    public static final int AppCompatTheme_dropdownListPreferredItemHeight = 46;
    public static final int AppCompatTheme_editTextBackground = 63;
    public static final int AppCompatTheme_editTextColor = 62;
    public static final int AppCompatTheme_editTextStyle = 104;
    public static final int AppCompatTheme_homeAsUpIndicator = 48;
    public static final int AppCompatTheme_imageButtonStyle = 64;
    public static final int AppCompatTheme_listChoiceBackgroundIndicator = 81;
    public static final int AppCompatTheme_listDividerAlertDialog = 44;
    public static final int AppCompatTheme_listPopupWindowStyle = 75;
    public static final int AppCompatTheme_listPreferredItemHeight = 69;
    public static final int AppCompatTheme_listPreferredItemHeightLarge = 71;
    public static final int AppCompatTheme_listPreferredItemHeightSmall = 70;
    public static final int AppCompatTheme_listPreferredItemPaddingLeft = 72;
    public static final int AppCompatTheme_listPreferredItemPaddingRight = 73;
    public static final int AppCompatTheme_panelBackground = 78;
    public static final int AppCompatTheme_panelMenuListTheme = 80;
    public static final int AppCompatTheme_panelMenuListWidth = 79;
    public static final int AppCompatTheme_popupMenuStyle = 60;
    public static final int AppCompatTheme_popupWindowStyle = 61;
    public static final int AppCompatTheme_radioButtonStyle = 105;
    public static final int AppCompatTheme_ratingBarStyle = 106;
    public static final int AppCompatTheme_ratingBarStyleIndicator = 107;
    public static final int AppCompatTheme_ratingBarStyleSmall = 108;
    public static final int AppCompatTheme_searchViewStyle = 68;
    public static final int AppCompatTheme_seekBarStyle = 109;
    public static final int AppCompatTheme_selectableItemBackground = 52;
    public static final int AppCompatTheme_selectableItemBackgroundBorderless = 53;
    public static final int AppCompatTheme_spinnerDropDownItemStyle = 47;
    public static final int AppCompatTheme_spinnerStyle = 110;
    public static final int AppCompatTheme_switchStyle = 111;
    public static final int AppCompatTheme_textAppearanceLargePopupMenu = 40;
    public static final int AppCompatTheme_textAppearanceListItem = 76;
    public static final int AppCompatTheme_textAppearanceListItemSmall = 77;
    public static final int AppCompatTheme_textAppearanceSearchResultSubtitle = 66;
    public static final int AppCompatTheme_textAppearanceSearchResultTitle = 65;
    public static final int AppCompatTheme_textAppearanceSmallPopupMenu = 41;
    public static final int AppCompatTheme_textColorAlertDialogListItem = 95;
    public static final int AppCompatTheme_textColorSearchUrl = 67;
    public static final int AppCompatTheme_toolbarNavigationButtonStyle = 59;
    public static final int AppCompatTheme_toolbarStyle = 58;
    public static final int AppCompatTheme_windowActionBar = 2;
    public static final int AppCompatTheme_windowActionBarOverlay = 4;
    public static final int AppCompatTheme_windowActionModeOverlay = 5;
    public static final int AppCompatTheme_windowFixedHeightMajor = 9;
    public static final int AppCompatTheme_windowFixedHeightMinor = 7;
    public static final int AppCompatTheme_windowFixedWidthMajor = 6;
    public static final int AppCompatTheme_windowFixedWidthMinor = 8;
    public static final int AppCompatTheme_windowMinWidthMajor = 10;
    public static final int AppCompatTheme_windowMinWidthMinor = 11;
    public static final int AppCompatTheme_windowNoTitle = 3;
    public static final int[] AspectRatioFrameLayout;
    public static final int AspectRatioFrameLayout_aspect_ratio = 0;
    public static final int AspectRatioFrameLayout_max_aspect_ratio = 2;
    public static final int AspectRatioFrameLayout_max_height = 4;
    public static final int AspectRatioFrameLayout_max_width = 3;
    public static final int AspectRatioFrameLayout_min_aspect_ratio = 1;
    public static final int AspectRatioFrameLayout_scaleMode = 5;
    public static final int[] BackgroundImageView;
    public static final int BackgroundImageView_crossfadeDuration = 1;
    public static final int BackgroundImageView_filterColor = 3;
    public static final int BackgroundImageView_filterMaxOpacity = 2;
    public static final int BackgroundImageView_overlayDrawable = 0;
    public static final int[] BadgeView;
    public static final int BadgeView_android_lineSpacingExtra = 1;
    public static final int BadgeView_android_lineSpacingMultiplier = 2;
    public static final int BadgeView_android_textSize = 0;
    public static final int BadgeView_badgeSpacing = 3;
    public static final int BadgeView_contentColor = 4;
    public static final int BadgeView_showBadge = 5;
    public static final int[] BaseMediaImageView;
    public static final int BaseMediaImageView_defaultDrawable = 0;
    public static final int BaseMediaImageView_errorDrawable = 1;
    public static final int BaseMediaImageView_imageType = 2;
    public static final int BaseMediaImageView_scaleType = 4;
    public static final int BaseMediaImageView_updateOnResize = 3;
    public static final int[] BottomSheetBehavior_Params;
    public static final int BottomSheetBehavior_Params_behavior_hideable = 1;
    public static final int BottomSheetBehavior_Params_behavior_peekHeight = 0;
    public static final int[] ButtonBarLayout;
    public static final int ButtonBarLayout_allowStacking = 0;
    public static final int[] CellLayout_Layout;
    public static final int CellLayout_Layout_android_layout_gravity = 0;
    public static final int[] CollapsingAppBarLayout_LayoutParams;
    public static final int CollapsingAppBarLayout_LayoutParams_layout_collapseMode = 0;
    public static final int CollapsingAppBarLayout_LayoutParams_layout_collapseParallaxMultiplier = 1;
    public static final int[] CollapsingToolbarLayout;
    public static final int CollapsingToolbarLayout_collapsedTitleGravity = 11;
    public static final int CollapsingToolbarLayout_collapsedTitleTextAppearance = 7;
    public static final int CollapsingToolbarLayout_contentScrim = 8;
    public static final int CollapsingToolbarLayout_expandedTitleGravity = 12;
    public static final int CollapsingToolbarLayout_expandedTitleMargin = 1;
    public static final int CollapsingToolbarLayout_expandedTitleMarginBottom = 5;
    public static final int CollapsingToolbarLayout_expandedTitleMarginEnd = 4;
    public static final int CollapsingToolbarLayout_expandedTitleMarginStart = 2;
    public static final int CollapsingToolbarLayout_expandedTitleMarginTop = 3;
    public static final int CollapsingToolbarLayout_expandedTitleTextAppearance = 6;
    public static final int CollapsingToolbarLayout_statusBarScrim = 9;
    public static final int CollapsingToolbarLayout_title = 0;
    public static final int CollapsingToolbarLayout_titleEnabled = 13;
    public static final int CollapsingToolbarLayout_toolbarId = 10;
    public static final int[] CompoundButton;
    public static final int CompoundButton_android_button = 0;
    public static final int CompoundButton_buttonTint = 1;
    public static final int CompoundButton_buttonTintMode = 2;
    public static final int[] CoordinatorLayout;
    public static final int[] CoordinatorLayout_LayoutParams;
    public static final int CoordinatorLayout_LayoutParams_android_layout_gravity = 0;
    public static final int CoordinatorLayout_LayoutParams_layout_anchor = 2;
    public static final int CoordinatorLayout_LayoutParams_layout_anchorGravity = 4;
    public static final int CoordinatorLayout_LayoutParams_layout_behavior = 1;
    public static final int CoordinatorLayout_LayoutParams_layout_keyline = 3;
    public static final int CoordinatorLayout_keylines = 0;
    public static final int CoordinatorLayout_statusBarBackground = 1;
    public static final int[] DesignTheme;
    public static final int DesignTheme_bottomSheetDialogTheme = 0;
    public static final int DesignTheme_bottomSheetStyle = 1;
    public static final int DesignTheme_textColorError = 2;
    public static final int[] DrawerArrowToggle;
    public static final int DrawerArrowToggle_arrowHeadLength = 4;
    public static final int DrawerArrowToggle_arrowShaftLength = 5;
    public static final int DrawerArrowToggle_barLength = 6;
    public static final int DrawerArrowToggle_color = 0;
    public static final int DrawerArrowToggle_drawableSize = 2;
    public static final int DrawerArrowToggle_gapBetweenBars = 3;
    public static final int DrawerArrowToggle_spinBars = 1;
    public static final int DrawerArrowToggle_thickness = 7;
    public static final int[] FixedSizeImageView;
    public static final int FixedSizeImageView_fixedSize = 0;
    public static final int[] FloatingActionButton;
    public static final int FloatingActionButton_backgroundTint = 6;
    public static final int FloatingActionButton_backgroundTintMode = 7;
    public static final int FloatingActionButton_borderWidth = 4;
    public static final int FloatingActionButton_elevation = 0;
    public static final int FloatingActionButton_fabSize = 2;
    public static final int FloatingActionButton_pressedTranslationZ = 3;
    public static final int FloatingActionButton_rippleColor = 1;
    public static final int FloatingActionButton_useCompatPadding = 5;
    public static final int[] ForegroundLinearLayout;
    public static final int ForegroundLinearLayout_android_foreground = 0;
    public static final int ForegroundLinearLayout_android_foregroundGravity = 1;
    public static final int ForegroundLinearLayout_foregroundInsidePadding = 2;
    public static final int[] LinearLayoutCompat;
    public static final int[] LinearLayoutCompat_Layout;
    public static final int LinearLayoutCompat_Layout_android_layout_gravity = 0;
    public static final int LinearLayoutCompat_Layout_android_layout_height = 2;
    public static final int LinearLayoutCompat_Layout_android_layout_weight = 3;
    public static final int LinearLayoutCompat_Layout_android_layout_width = 1;
    public static final int LinearLayoutCompat_android_baselineAligned = 2;
    public static final int LinearLayoutCompat_android_baselineAlignedChildIndex = 3;
    public static final int LinearLayoutCompat_android_gravity = 0;
    public static final int LinearLayoutCompat_android_orientation = 1;
    public static final int LinearLayoutCompat_android_weightSum = 4;
    public static final int LinearLayoutCompat_divider = 5;
    public static final int LinearLayoutCompat_dividerPadding = 8;
    public static final int LinearLayoutCompat_measureWithLargestChild = 6;
    public static final int LinearLayoutCompat_showDividers = 7;
    public static final int[] ListPopupWindow;
    public static final int ListPopupWindow_android_dropDownHorizontalOffset = 0;
    public static final int ListPopupWindow_android_dropDownVerticalOffset = 1;
    public static final int[] MediaImageView;
    public static final int MediaImageView_fadeIn = 0;
    public static final int MediaImageView_loadingProgressBar = 3;
    public static final int MediaImageView_scaleFactor = 2;
    public static final int MediaImageView_singleImageView = 1;
    public static final int[] MenuGroup;
    public static final int MenuGroup_android_checkableBehavior = 5;
    public static final int MenuGroup_android_enabled = 0;
    public static final int MenuGroup_android_id = 1;
    public static final int MenuGroup_android_menuCategory = 3;
    public static final int MenuGroup_android_orderInCategory = 4;
    public static final int MenuGroup_android_visible = 2;
    public static final int[] MenuItem;
    public static final int MenuItem_actionLayout = 14;
    public static final int MenuItem_actionProviderClass = 16;
    public static final int MenuItem_actionViewClass = 15;
    public static final int MenuItem_android_alphabeticShortcut = 9;
    public static final int MenuItem_android_checkable = 11;
    public static final int MenuItem_android_checked = 3;
    public static final int MenuItem_android_enabled = 1;
    public static final int MenuItem_android_icon = 0;
    public static final int MenuItem_android_id = 2;
    public static final int MenuItem_android_menuCategory = 5;
    public static final int MenuItem_android_numericShortcut = 10;
    public static final int MenuItem_android_onClick = 12;
    public static final int MenuItem_android_orderInCategory = 6;
    public static final int MenuItem_android_title = 7;
    public static final int MenuItem_android_titleCondensed = 8;
    public static final int MenuItem_android_visible = 4;
    public static final int MenuItem_showAsAction = 13;
    public static final int[] MenuView;
    public static final int MenuView_android_headerBackground = 4;
    public static final int MenuView_android_horizontalDivider = 2;
    public static final int MenuView_android_itemBackground = 5;
    public static final int MenuView_android_itemIconDisabledAlpha = 6;
    public static final int MenuView_android_itemTextAppearance = 1;
    public static final int MenuView_android_verticalDivider = 3;
    public static final int MenuView_android_windowAnimationStyle = 0;
    public static final int MenuView_preserveIconSpacing = 7;
    public static final int[] NavigationView;
    public static final int NavigationView_android_background = 0;
    public static final int NavigationView_android_fitsSystemWindows = 1;
    public static final int NavigationView_android_maxWidth = 2;
    public static final int NavigationView_elevation = 3;
    public static final int NavigationView_headerLayout = 9;
    public static final int NavigationView_itemBackground = 7;
    public static final int NavigationView_itemIconTint = 5;
    public static final int NavigationView_itemTextAppearance = 8;
    public static final int NavigationView_itemTextColor = 6;
    public static final int NavigationView_menu = 4;
    public static final int[] PopupWindow;
    public static final int[] PopupWindowBackgroundState;
    public static final int PopupWindowBackgroundState_state_above_anchor = 0;
    public static final int PopupWindow_android_popupBackground = 0;
    public static final int PopupWindow_overlapAnchor = 1;
    public static final int[] ProgressLayout;
    public static final int ProgressLayout_android_max = 0;
    public static final int[] PromptView;
    public static final int PromptView_buttonText = 2;
    public static final int PromptView_isHeader = 4;
    public static final int PromptView_showDismiss = 3;
    public static final int PromptView_subtitleText = 1;
    public static final int PromptView_titleText = 0;
    public static final int[] RecyclerView;
    public static final int RecyclerView_android_orientation = 0;
    public static final int RecyclerView_layoutManager = 1;
    public static final int RecyclerView_reverseLayout = 3;
    public static final int RecyclerView_spanCount = 2;
    public static final int RecyclerView_stackFromEnd = 4;
    public static final int[] RichImageView;
    public static final int RichImageView_cornerRadius = 0;
    public static final int RichImageView_cornerRadiusBottomLeft = 4;
    public static final int RichImageView_cornerRadiusBottomRight = 5;
    public static final int RichImageView_cornerRadiusTopLeft = 2;
    public static final int RichImageView_cornerRadiusTopRight = 3;
    public static final int RichImageView_overlayDrawable = 1;
    public static final int[] SVGImageView;
    public static final int SVGImageView_svg = 0;
    public static final int[] ScrimInsetsFrameLayout;
    public static final int ScrimInsetsFrameLayout_insetForeground = 0;
    public static final int[] ScrollingViewBehavior_Params;
    public static final int ScrollingViewBehavior_Params_behavior_overlapTop = 0;
    public static final int[] SearchView;
    public static final int SearchView_android_focusable = 0;
    public static final int SearchView_android_imeOptions = 3;
    public static final int SearchView_android_inputType = 2;
    public static final int SearchView_android_maxWidth = 1;
    public static final int SearchView_closeIcon = 8;
    public static final int SearchView_commitIcon = 13;
    public static final int SearchView_defaultQueryHint = 7;
    public static final int SearchView_goIcon = 9;
    public static final int SearchView_iconifiedByDefault = 5;
    public static final int SearchView_layout = 4;
    public static final int SearchView_queryBackground = 15;
    public static final int SearchView_queryHint = 6;
    public static final int SearchView_searchHintIcon = 11;
    public static final int SearchView_searchIcon = 10;
    public static final int SearchView_submitBackground = 16;
    public static final int SearchView_suggestionRowLayout = 14;
    public static final int SearchView_voiceIcon = 12;
    public static final int[] SlidingTabLayout;
    public static final int SlidingTabLayout_bottomBorderColor = 2;
    public static final int SlidingTabLayout_bottomBorderThickness = 1;
    public static final int SlidingTabLayout_selectedIndicatorColor = 4;
    public static final int SlidingTabLayout_selectedIndicatorThickness = 3;
    public static final int SlidingTabLayout_tabDividerColor = 5;
    public static final int SlidingTabLayout_titleOffset = 0;
    public static final int[] SnackbarLayout;
    public static final int SnackbarLayout_android_maxWidth = 0;
    public static final int SnackbarLayout_elevation = 1;
    public static final int SnackbarLayout_maxActionInlineWidth = 2;
    public static final int[] Spinner;
    public static final int Spinner_android_dropDownWidth = 3;
    public static final int Spinner_android_entries = 0;
    public static final int Spinner_android_popupBackground = 1;
    public static final int Spinner_android_prompt = 2;
    public static final int Spinner_popupTheme = 4;
    public static final int[] SwitchCompat;
    public static final int SwitchCompat_android_textOff = 1;
    public static final int SwitchCompat_android_textOn = 0;
    public static final int SwitchCompat_android_thumb = 2;
    public static final int SwitchCompat_showText = 9;
    public static final int SwitchCompat_splitTrack = 8;
    public static final int SwitchCompat_switchMinWidth = 6;
    public static final int SwitchCompat_switchPadding = 7;
    public static final int SwitchCompat_switchTextAppearance = 5;
    public static final int SwitchCompat_thumbTextPadding = 4;
    public static final int SwitchCompat_track = 3;
    public static final int[] TabItem;
    public static final int TabItem_android_icon = 0;
    public static final int TabItem_android_layout = 1;
    public static final int TabItem_android_text = 2;
    public static final int[] TabLayout;
    public static final int TabLayout_tabBackground = 3;
    public static final int TabLayout_tabContentStart = 2;
    public static final int TabLayout_tabGravity = 5;
    public static final int TabLayout_tabIndicatorColor = 0;
    public static final int TabLayout_tabIndicatorHeight = 1;
    public static final int TabLayout_tabMaxWidth = 7;
    public static final int TabLayout_tabMinWidth = 6;
    public static final int TabLayout_tabMode = 4;
    public static final int TabLayout_tabPadding = 15;
    public static final int TabLayout_tabPaddingBottom = 14;
    public static final int TabLayout_tabPaddingEnd = 13;
    public static final int TabLayout_tabPaddingStart = 11;
    public static final int TabLayout_tabPaddingTop = 12;
    public static final int TabLayout_tabSelectedTextColor = 10;
    public static final int TabLayout_tabTextAppearance = 8;
    public static final int TabLayout_tabTextColor = 9;
    public static final int[] TextAppearance;
    public static final int TextAppearance_android_shadowColor = 4;
    public static final int TextAppearance_android_shadowDx = 5;
    public static final int TextAppearance_android_shadowDy = 6;
    public static final int TextAppearance_android_shadowRadius = 7;
    public static final int TextAppearance_android_textColor = 3;
    public static final int TextAppearance_android_textSize = 0;
    public static final int TextAppearance_android_textStyle = 2;
    public static final int TextAppearance_android_typeface = 1;
    public static final int TextAppearance_textAllCaps = 8;
    public static final int[] TextInputLayout;
    public static final int TextInputLayout_android_hint = 1;
    public static final int TextInputLayout_android_textColorHint = 0;
    public static final int TextInputLayout_counterEnabled = 6;
    public static final int TextInputLayout_counterMaxLength = 7;
    public static final int TextInputLayout_counterOverflowTextAppearance = 9;
    public static final int TextInputLayout_counterTextAppearance = 8;
    public static final int TextInputLayout_errorEnabled = 4;
    public static final int TextInputLayout_errorTextAppearance = 5;
    public static final int TextInputLayout_hintAnimationEnabled = 10;
    public static final int TextInputLayout_hintEnabled = 3;
    public static final int TextInputLayout_hintTextAppearance = 2;
    public static final int[] TextLayoutView;
    public static final int TextLayoutView_android_lineSpacingExtra = 3;
    public static final int TextLayoutView_android_lineSpacingMultiplier = 4;
    public static final int TextLayoutView_android_text = 2;
    public static final int TextLayoutView_android_textColor = 1;
    public static final int TextLayoutView_android_textSize = 0;
    public static final int[] TintableImageView;
    public static final int TintableImageView_tintColorList = 0;
    public static final int[] ToggleTwitterButton;
    public static final int ToggleTwitterButton_initOn = 4;
    public static final int ToggleTwitterButton_shouldToggleOnClick = 3;
    public static final int ToggleTwitterButton_showIconOn = 2;
    public static final int ToggleTwitterButton_styleIdOff = 1;
    public static final int ToggleTwitterButton_styleIdOn = 0;
    public static final int[] Toolbar;
    public static final int Toolbar_android_gravity = 0;
    public static final int Toolbar_android_minHeight = 1;
    public static final int Toolbar_collapseContentDescription = 19;
    public static final int Toolbar_collapseIcon = 18;
    public static final int Toolbar_contentInsetEnd = 6;
    public static final int Toolbar_contentInsetLeft = 7;
    public static final int Toolbar_contentInsetRight = 8;
    public static final int Toolbar_contentInsetStart = 5;
    public static final int Toolbar_logo = 4;
    public static final int Toolbar_logoDescription = 22;
    public static final int Toolbar_maxButtonHeight = 17;
    public static final int Toolbar_navigationContentDescription = 21;
    public static final int Toolbar_navigationIcon = 20;
    public static final int Toolbar_popupTheme = 9;
    public static final int Toolbar_subtitle = 3;
    public static final int Toolbar_subtitleTextAppearance = 11;
    public static final int Toolbar_subtitleTextColor = 24;
    public static final int Toolbar_title = 2;
    public static final int Toolbar_titleMarginBottom = 16;
    public static final int Toolbar_titleMarginEnd = 14;
    public static final int Toolbar_titleMarginStart = 13;
    public static final int Toolbar_titleMarginTop = 15;
    public static final int Toolbar_titleMargins = 12;
    public static final int Toolbar_titleTextAppearance = 10;
    public static final int Toolbar_titleTextColor = 23;
    public static final int[] TooltipView;
    public static final int TooltipView_arrowHeight = 6;
    public static final int TooltipView_arrowWidth = 5;
    public static final int TooltipView_cornerRadius = 0;
    public static final int TooltipView_screenEdgePadding = 7;
    public static final int TooltipView_textAppearance = 4;
    public static final int TooltipView_tooltipColor = 3;
    public static final int TooltipView_transitionAnimationDelayMs = 8;
    public static final int TooltipView_xOffset = 1;
    public static final int TooltipView_yOffset = 2;
    public static final int[] TouchForwardingFrameLayout;
    public static final int TouchForwardingFrameLayout_targetViewGroup = 0;
    public static final int[] TwitterButton;
    public static final int TwitterButton_bounded = 17;
    public static final int TwitterButton_buttonStyle = 2;
    public static final int TwitterButton_cornerRadius = 0;
    public static final int TwitterButton_fillColor = 6;
    public static final int TwitterButton_fillPressedColor = 7;
    public static final int TwitterButton_iconAndLabelMargin = 13;
    public static final int TwitterButton_iconCanBeFlipped = 11;
    public static final int TwitterButton_iconColor = 8;
    public static final int TwitterButton_iconLayout = 19;
    public static final int TwitterButton_iconMargin = 12;
    public static final int TwitterButton_iconPressedColor = 9;
    public static final int TwitterButton_iconSize = 10;
    public static final int TwitterButton_knockout = 18;
    public static final int TwitterButton_labelColor = 1;
    public static final int TwitterButton_labelMargin = 14;
    public static final int TwitterButton_labelPressedColor = 5;
    public static final int TwitterButton_nodpiBaseIconName = 16;
    public static final int TwitterButton_strokeColor = 3;
    public static final int TwitterButton_strokePressedColor = 4;
    public static final int TwitterButton_strokeWidth = 15;
    public static final int[] TwitterEditText;
    public static final int TwitterEditText_characterCounterColor = 12;
    public static final int TwitterEditText_characterCounterMode = 13;
    public static final int TwitterEditText_helperMessage = 7;
    public static final int TwitterEditText_labelColor = 0;
    public static final int TwitterEditText_labelSize = 1;
    public static final int TwitterEditText_labelStyle = 3;
    public static final int TwitterEditText_labelText = 2;
    public static final int TwitterEditText_maxCharacterCount = 11;
    public static final int TwitterEditText_messageColor = 8;
    public static final int TwitterEditText_messageSize = 9;
    public static final int TwitterEditText_messageStyle = 10;
    public static final int TwitterEditText_statusIcon = 5;
    public static final int TwitterEditText_statusIconPosition = 6;
    public static final int TwitterEditText_underlineStyle = 4;
    public static final int[] TwitterIndeterminateProgressSpinner;
    public static final int TwitterIndeterminateProgressSpinner_logoSize = 0;
    public static final int TwitterIndeterminateProgressSpinner_ringSize = 1;
    public static final int TwitterIndeterminateProgressSpinner_ringThickness = 2;
    public static final int TwitterIndeterminateProgressSpinner_whiteForeground = 3;
    public static final int[] TwitterSelection;
    public static final int TwitterSelection_dialogTheme = 1;
    public static final int TwitterSelection_displayLayout = 4;
    public static final int TwitterSelection_dropDownAnchor = 5;
    public static final int TwitterSelection_dropDownHeight = 7;
    public static final int TwitterSelection_dropDownWidth = 6;
    public static final int TwitterSelection_listLayout = 0;
    public static final int TwitterSelection_selectionMode = 2;
    public static final int TwitterSelection_showPopupOnClick = 3;
    public static final int[] UnderlineDrawable;
    public static final int UnderlineDrawable_android_color = 0;
    public static final int UnderlineDrawable_android_left = 1;
    public static final int UnderlineDrawable_android_right = 2;
    public static final int[] View;
    public static final int[] ViewBackgroundHelper;
    public static final int ViewBackgroundHelper_android_background = 0;
    public static final int ViewBackgroundHelper_backgroundTint = 1;
    public static final int ViewBackgroundHelper_backgroundTintMode = 2;
    public static final int[] ViewStates;
    public static final int ViewStates_state_blank = 2;
    public static final int ViewStates_state_error = 1;
    public static final int ViewStates_state_fault = 0;
    public static final int ViewStates_state_validated = 3;
    public static final int[] ViewStubCompat;
    public static final int ViewStubCompat_android_id = 0;
    public static final int ViewStubCompat_android_inflatedId = 2;
    public static final int ViewStubCompat_android_layout = 1;
    public static final int View_android_focusable = 1;
    public static final int View_android_theme = 0;
    public static final int View_paddingEnd = 3;
    public static final int View_paddingStart = 2;
    public static final int View_theme = 4;

    static {
        ActionBar = new int[]{crv.height, crv.title, crv.navigationMode, crv.displayOptions, crv.subtitle, crv.titleTextStyle, crv.subtitleTextStyle, crv.icon, crv.logo, crv.divider, crv.background, crv.backgroundStacked, crv.backgroundSplit, crv.customNavigationLayout, crv.homeLayout, crv.progressBarStyle, crv.indeterminateProgressStyle, crv.progressBarPadding, crv.itemPadding, crv.hideOnContentScroll, crv.contentInsetStart, crv.contentInsetEnd, crv.contentInsetLeft, crv.contentInsetRight, crv.elevation, crv.popupTheme, crv.homeAsUpIndicator};
        int[] iArr = new int[View_android_focusable];
        iArr[View_android_theme] = 16842931;
        ActionBarLayout = iArr;
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = 16843071;
        ActionMenuItemView = iArr;
        ActionMenuView = new int[View_android_theme];
        ActionMode = new int[]{crv.height, crv.titleTextStyle, crv.subtitleTextStyle, crv.background, crv.backgroundSplit, crv.closeItemLayout};
        ActivityChooserView = new int[]{crv.initialActivityCount, crv.expandActivityOverflowButtonDrawable};
        AlertDialog = new int[]{16842994, crv.buttonPanelSideLayout, crv.listLayout, crv.multiChoiceItemLayout, crv.singleChoiceItemLayout, crv.listItemLayout};
        AppBarLayout = new int[]{16842964, crv.elevation, crv.expanded};
        AppBarLayout_LayoutParams = new int[]{crv.layout_scrollFlags, crv.layout_scrollInterpolator};
        AppCompatImageView = new int[]{16843033, crv.srcCompat};
        AppCompatTextView = new int[]{16842804, crv.textAllCaps};
        AppCompatTheme = new int[]{16842839, 16842926, crv.windowActionBar, crv.windowNoTitle, crv.windowActionBarOverlay, crv.windowActionModeOverlay, crv.windowFixedWidthMajor, crv.windowFixedHeightMinor, crv.windowFixedWidthMinor, crv.windowFixedHeightMajor, crv.windowMinWidthMajor, crv.windowMinWidthMinor, crv.actionBarTabStyle, crv.actionBarTabBarStyle, crv.actionBarTabTextStyle, crv.actionOverflowButtonStyle, crv.actionOverflowMenuStyle, crv.actionBarPopupTheme, crv.actionBarStyle, crv.actionBarSplitStyle, crv.actionBarTheme, crv.actionBarWidgetTheme, crv.actionBarSize, crv.actionBarDivider, crv.actionBarItemBackground, crv.actionMenuTextAppearance, crv.actionMenuTextColor, crv.actionModeStyle, crv.actionModeCloseButtonStyle, crv.actionModeBackground, crv.actionModeSplitBackground, crv.actionModeCloseDrawable, crv.actionModeCutDrawable, crv.actionModeCopyDrawable, crv.actionModePasteDrawable, crv.actionModeSelectAllDrawable, crv.actionModeShareDrawable, crv.actionModeFindDrawable, crv.actionModeWebSearchDrawable, crv.actionModePopupWindowStyle, crv.textAppearanceLargePopupMenu, crv.textAppearanceSmallPopupMenu, crv.dialogTheme, crv.dialogPreferredPadding, crv.listDividerAlertDialog, crv.actionDropDownStyle, crv.dropdownListPreferredItemHeight, crv.spinnerDropDownItemStyle, crv.homeAsUpIndicator, crv.actionButtonStyle, crv.buttonBarStyle, crv.buttonBarButtonStyle, crv.selectableItemBackground, crv.selectableItemBackgroundBorderless, crv.borderlessButtonStyle, crv.dividerVertical, crv.dividerHorizontal, crv.activityChooserViewStyle, crv.toolbarStyle, crv.toolbarNavigationButtonStyle, crv.popupMenuStyle, crv.popupWindowStyle, crv.editTextColor, crv.editTextBackground, crv.imageButtonStyle, crv.textAppearanceSearchResultTitle, crv.textAppearanceSearchResultSubtitle, crv.textColorSearchUrl, crv.searchViewStyle, crv.listPreferredItemHeight, crv.listPreferredItemHeightSmall, crv.listPreferredItemHeightLarge, crv.listPreferredItemPaddingLeft, crv.listPreferredItemPaddingRight, crv.dropDownListViewStyle, crv.listPopupWindowStyle, crv.textAppearanceListItem, crv.textAppearanceListItemSmall, crv.panelBackground, crv.panelMenuListWidth, crv.panelMenuListTheme, crv.listChoiceBackgroundIndicator, crv.colorPrimary, crv.colorPrimaryDark, crv.colorAccent, crv.colorControlNormal, crv.colorControlActivated, crv.colorControlHighlight, crv.colorButtonNormal, crv.colorSwitchThumbNormal, crv.controlBackground, crv.alertDialogStyle, crv.alertDialogButtonGroupStyle, crv.alertDialogCenterButtons, crv.alertDialogTheme, crv.textColorAlertDialogListItem, crv.buttonBarPositiveButtonStyle, crv.buttonBarNegativeButtonStyle, crv.buttonBarNeutralButtonStyle, crv.autoCompleteTextViewStyle, crv.buttonStyle, crv.buttonStyleSmall, crv.checkboxStyle, crv.checkedTextViewStyle, crv.editTextStyle, crv.radioButtonStyle, crv.ratingBarStyle, crv.ratingBarStyleIndicator, crv.ratingBarStyleSmall, crv.seekBarStyle, crv.spinnerStyle, crv.switchStyle};
        AspectRatioFrameLayout = new int[]{crv.aspect_ratio, crv.min_aspect_ratio, crv.max_aspect_ratio, crv.max_width, crv.max_height, crv.scaleMode};
        BackgroundImageView = new int[]{crv.overlayDrawable, crv.crossfadeDuration, crv.filterMaxOpacity, crv.filterColor};
        BadgeView = new int[]{16842901, 16843287, 16843288, crv.badgeSpacing, crv.contentColor, crv.showBadge};
        BaseMediaImageView = new int[]{crv.defaultDrawable, crv.errorDrawable, crv.imageType, crv.updateOnResize, crv.scaleType};
        BottomSheetBehavior_Params = new int[]{crv.behavior_peekHeight, crv.behavior_hideable};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = crv.allowStacking;
        ButtonBarLayout = iArr;
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = 16842931;
        CellLayout_Layout = iArr;
        CollapsingAppBarLayout_LayoutParams = new int[]{crv.layout_collapseMode, crv.layout_collapseParallaxMultiplier};
        CollapsingToolbarLayout = new int[]{crv.title, crv.expandedTitleMargin, crv.expandedTitleMarginStart, crv.expandedTitleMarginTop, crv.expandedTitleMarginEnd, crv.expandedTitleMarginBottom, crv.expandedTitleTextAppearance, crv.collapsedTitleTextAppearance, crv.contentScrim, crv.statusBarScrim, crv.toolbarId, crv.collapsedTitleGravity, crv.expandedTitleGravity, crv.titleEnabled};
        CompoundButton = new int[]{16843015, crv.buttonTint, crv.buttonTintMode};
        CoordinatorLayout = new int[]{crv.keylines, crv.statusBarBackground};
        CoordinatorLayout_LayoutParams = new int[]{16842931, crv.layout_behavior, crv.layout_anchor, crv.layout_keyline, crv.layout_anchorGravity};
        DesignTheme = new int[]{crv.bottomSheetDialogTheme, crv.bottomSheetStyle, crv.textColorError};
        DrawerArrowToggle = new int[]{crv.color, crv.spinBars, crv.drawableSize, crv.gapBetweenBars, crv.arrowHeadLength, crv.arrowShaftLength, crv.barLength, crv.thickness};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = crv.fixedSize;
        FixedSizeImageView = iArr;
        FloatingActionButton = new int[]{crv.elevation, crv.rippleColor, crv.fabSize, crv.pressedTranslationZ, crv.borderWidth, crv.useCompatPadding, crv.backgroundTint, crv.backgroundTintMode};
        ForegroundLinearLayout = new int[]{16843017, 16843264, crv.foregroundInsidePadding};
        LinearLayoutCompat = new int[]{16842927, 16842948, 16843046, 16843047, 16843048, crv.divider, crv.measureWithLargestChild, crv.showDividers, crv.dividerPadding};
        LinearLayoutCompat_Layout = new int[]{16842931, 16842996, 16842997, 16843137};
        ListPopupWindow = new int[]{16843436, 16843437};
        MediaImageView = new int[]{crv.fadeIn, crv.singleImageView, crv.scaleFactor, crv.loadingProgressBar};
        MenuGroup = new int[]{16842766, 16842960, 16843156, 16843230, 16843231, 16843232};
        MenuItem = new int[]{16842754, 16842766, 16842960, 16843014, 16843156, 16843230, 16843231, 16843233, 16843234, 16843235, 16843236, 16843237, 16843375, crv.showAsAction, crv.actionLayout, crv.actionViewClass, crv.actionProviderClass};
        MenuView = new int[]{16842926, 16843052, 16843053, 16843054, 16843055, 16843056, 16843057, crv.preserveIconSpacing};
        NavigationView = new int[]{16842964, 16842973, 16843039, crv.elevation, crv.menu, crv.itemIconTint, crv.itemTextColor, crv.itemBackground, crv.itemTextAppearance, crv.headerLayout};
        PopupWindow = new int[]{16843126, crv.overlapAnchor};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = crv.state_above_anchor;
        PopupWindowBackgroundState = iArr;
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = 16843062;
        ProgressLayout = iArr;
        PromptView = new int[]{crv.titleText, crv.subtitleText, crv.buttonText, crv.showDismiss, crv.isHeader};
        RecyclerView = new int[]{16842948, crv.layoutManager, crv.spanCount, crv.reverseLayout, crv.stackFromEnd};
        RichImageView = new int[]{crv.cornerRadius, crv.overlayDrawable, crv.cornerRadiusTopLeft, crv.cornerRadiusTopRight, crv.cornerRadiusBottomLeft, crv.cornerRadiusBottomRight};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = crv.svg;
        SVGImageView = iArr;
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = crv.insetForeground;
        ScrimInsetsFrameLayout = iArr;
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = crv.behavior_overlapTop;
        ScrollingViewBehavior_Params = iArr;
        SearchView = new int[]{16842970, 16843039, 16843296, 16843364, crv.layout, crv.iconifiedByDefault, crv.queryHint, crv.defaultQueryHint, crv.closeIcon, crv.goIcon, crv.searchIcon, crv.searchHintIcon, crv.voiceIcon, crv.commitIcon, crv.suggestionRowLayout, crv.queryBackground, crv.submitBackground};
        SlidingTabLayout = new int[]{crv.titleOffset, crv.bottomBorderThickness, crv.bottomBorderColor, crv.selectedIndicatorThickness, crv.selectedIndicatorColor, crv.tabDividerColor};
        SnackbarLayout = new int[]{16843039, crv.elevation, crv.maxActionInlineWidth};
        Spinner = new int[]{16842930, 16843126, 16843131, 16843362, crv.popupTheme};
        SwitchCompat = new int[]{16843044, 16843045, 16843074, crv.track, crv.thumbTextPadding, crv.switchTextAppearance, crv.switchMinWidth, crv.switchPadding, crv.splitTrack, crv.showText};
        TabItem = new int[]{16842754, 16842994, 16843087};
        TabLayout = new int[]{crv.tabIndicatorColor, crv.tabIndicatorHeight, crv.tabContentStart, crv.tabBackground, crv.tabMode, crv.tabGravity, crv.tabMinWidth, crv.tabMaxWidth, crv.tabTextAppearance, crv.tabTextColor, crv.tabSelectedTextColor, crv.tabPaddingStart, crv.tabPaddingTop, crv.tabPaddingEnd, crv.tabPaddingBottom, crv.tabPadding};
        TextAppearance = new int[]{16842901, 16842902, 16842903, 16842904, 16843105, 16843106, 16843107, 16843108, crv.textAllCaps};
        TextInputLayout = new int[]{16842906, 16843088, crv.hintTextAppearance, crv.hintEnabled, crv.errorEnabled, crv.errorTextAppearance, crv.counterEnabled, crv.counterMaxLength, crv.counterTextAppearance, crv.counterOverflowTextAppearance, crv.hintAnimationEnabled};
        TextLayoutView = new int[]{16842901, 16842904, 16843087, 16843287, 16843288};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = crv.tintColorList;
        TintableImageView = iArr;
        ToggleTwitterButton = new int[]{crv.styleIdOn, crv.styleIdOff, crv.showIconOn, crv.shouldToggleOnClick, crv.initOn};
        Toolbar = new int[]{16842927, 16843072, crv.title, crv.subtitle, crv.logo, crv.contentInsetStart, crv.contentInsetEnd, crv.contentInsetLeft, crv.contentInsetRight, crv.popupTheme, crv.titleTextAppearance, crv.subtitleTextAppearance, crv.titleMargins, crv.titleMarginStart, crv.titleMarginEnd, crv.titleMarginTop, crv.titleMarginBottom, crv.maxButtonHeight, crv.collapseIcon, crv.collapseContentDescription, crv.navigationIcon, crv.navigationContentDescription, crv.logoDescription, crv.titleTextColor, crv.subtitleTextColor};
        TooltipView = new int[]{crv.cornerRadius, crv.xOffset, crv.yOffset, crv.tooltipColor, crv.textAppearance, crv.arrowWidth, crv.arrowHeight, crv.screenEdgePadding, crv.transitionAnimationDelayMs};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = crv.targetViewGroup;
        TouchForwardingFrameLayout = iArr;
        TwitterButton = new int[]{crv.cornerRadius, crv.labelColor, crv.buttonStyle, crv.strokeColor, crv.strokePressedColor, crv.labelPressedColor, crv.fillColor, crv.fillPressedColor, crv.iconColor, crv.iconPressedColor, crv.iconSize, crv.iconCanBeFlipped, crv.iconMargin, crv.iconAndLabelMargin, crv.labelMargin, crv.strokeWidth, crv.nodpiBaseIconName, crv.bounded, crv.knockout, crv.iconLayout};
        TwitterEditText = new int[]{crv.labelColor, crv.labelSize, crv.labelText, crv.labelStyle, crv.underlineStyle, crv.statusIcon, crv.statusIconPosition, crv.helperMessage, crv.messageColor, crv.messageSize, crv.messageStyle, crv.maxCharacterCount, crv.characterCounterColor, crv.characterCounterMode};
        TwitterIndeterminateProgressSpinner = new int[]{crv.logoSize, crv.ringSize, crv.ringThickness, crv.whiteForeground};
        TwitterSelection = new int[]{crv.listLayout, crv.dialogTheme, crv.selectionMode, crv.showPopupOnClick, crv.displayLayout, crv.dropDownAnchor, crv.dropDownWidth, crv.dropDownHeight};
        UnderlineDrawable = new int[]{16843173, 16843181, 16843183};
        View = new int[]{16842752, 16842970, crv.paddingStart, crv.paddingEnd, crv.theme};
        ViewBackgroundHelper = new int[]{16842964, crv.backgroundTint, crv.backgroundTintMode};
        ViewStates = new int[]{crv.state_fault, crv.state_error, crv.state_blank, crv.state_validated};
        ViewStubCompat = new int[]{16842960, 16842994, 16842995};
    }
}
