package org.spongycastle.asn1.pkcs;

import org.spongycastle.asn1.ASN1ObjectIdentifier;

/* compiled from: Twttr */
public interface PKCSObjectIdentifiers {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier K;
    public static final ASN1ObjectIdentifier L;
    public static final ASN1ObjectIdentifier M;
    public static final ASN1ObjectIdentifier N;
    public static final ASN1ObjectIdentifier O;
    public static final ASN1ObjectIdentifier P;
    public static final ASN1ObjectIdentifier Q;
    public static final ASN1ObjectIdentifier R;
    public static final ASN1ObjectIdentifier S;
    public static final ASN1ObjectIdentifier T;
    public static final ASN1ObjectIdentifier U;
    public static final ASN1ObjectIdentifier V;
    public static final ASN1ObjectIdentifier W;
    public static final ASN1ObjectIdentifier X;
    public static final ASN1ObjectIdentifier Y;
    public static final ASN1ObjectIdentifier Z;
    public static final ASN1ObjectIdentifier aA;
    public static final ASN1ObjectIdentifier aB;
    public static final ASN1ObjectIdentifier aC;
    public static final ASN1ObjectIdentifier aD;
    public static final ASN1ObjectIdentifier aE;
    public static final ASN1ObjectIdentifier aF;
    public static final ASN1ObjectIdentifier aG;
    public static final ASN1ObjectIdentifier aH;
    public static final ASN1ObjectIdentifier aI;
    public static final ASN1ObjectIdentifier aJ;
    public static final ASN1ObjectIdentifier aK;
    public static final ASN1ObjectIdentifier aL;
    public static final ASN1ObjectIdentifier aM;
    public static final ASN1ObjectIdentifier aN;
    public static final ASN1ObjectIdentifier aO;
    public static final ASN1ObjectIdentifier aP;
    public static final ASN1ObjectIdentifier aQ;
    public static final ASN1ObjectIdentifier aR;
    public static final ASN1ObjectIdentifier aS;
    public static final ASN1ObjectIdentifier aT;
    public static final ASN1ObjectIdentifier aU;
    public static final ASN1ObjectIdentifier aV;
    public static final ASN1ObjectIdentifier aW;
    public static final ASN1ObjectIdentifier aX;
    public static final ASN1ObjectIdentifier aY;
    public static final ASN1ObjectIdentifier aZ;
    public static final ASN1ObjectIdentifier aa;
    public static final ASN1ObjectIdentifier ab;
    public static final ASN1ObjectIdentifier ac;
    public static final ASN1ObjectIdentifier ad;
    public static final ASN1ObjectIdentifier ae;
    public static final ASN1ObjectIdentifier af;
    public static final ASN1ObjectIdentifier ag;
    public static final ASN1ObjectIdentifier ah;
    public static final ASN1ObjectIdentifier ai;
    public static final ASN1ObjectIdentifier aj;
    public static final ASN1ObjectIdentifier ak;
    public static final ASN1ObjectIdentifier al;
    public static final ASN1ObjectIdentifier am;
    public static final ASN1ObjectIdentifier an;
    public static final ASN1ObjectIdentifier ao;
    public static final ASN1ObjectIdentifier ap;
    public static final ASN1ObjectIdentifier aq;
    public static final ASN1ObjectIdentifier ar;
    public static final ASN1ObjectIdentifier as;
    public static final ASN1ObjectIdentifier at;
    public static final ASN1ObjectIdentifier au;
    public static final ASN1ObjectIdentifier av;
    public static final ASN1ObjectIdentifier aw;
    public static final ASN1ObjectIdentifier ax;
    public static final ASN1ObjectIdentifier ay;
    public static final ASN1ObjectIdentifier az;
    public static final ASN1ObjectIdentifier bA;
    public static final ASN1ObjectIdentifier bB;
    public static final ASN1ObjectIdentifier bC;
    public static final ASN1ObjectIdentifier ba;
    public static final ASN1ObjectIdentifier bb;
    public static final ASN1ObjectIdentifier bc;
    public static final ASN1ObjectIdentifier bd;
    public static final ASN1ObjectIdentifier be;
    public static final ASN1ObjectIdentifier bf;
    public static final ASN1ObjectIdentifier bg;
    public static final ASN1ObjectIdentifier bh;
    public static final ASN1ObjectIdentifier bi;
    public static final ASN1ObjectIdentifier bj;
    public static final ASN1ObjectIdentifier bk;
    public static final ASN1ObjectIdentifier bl;
    public static final ASN1ObjectIdentifier bm;
    public static final ASN1ObjectIdentifier bn;
    public static final ASN1ObjectIdentifier bo;
    public static final ASN1ObjectIdentifier bp;
    public static final ASN1ObjectIdentifier bq;
    public static final ASN1ObjectIdentifier br;
    public static final ASN1ObjectIdentifier bs;
    public static final ASN1ObjectIdentifier bt;
    public static final ASN1ObjectIdentifier bu;
    public static final ASN1ObjectIdentifier bv;
    public static final ASN1ObjectIdentifier bw;
    public static final ASN1ObjectIdentifier bx;
    public static final ASN1ObjectIdentifier by;
    public static final ASN1ObjectIdentifier bz;
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier m_;
    public static final ASN1ObjectIdentifier n_;
    public static final ASN1ObjectIdentifier o_;
    public static final ASN1ObjectIdentifier p_;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier q_;
    public static final ASN1ObjectIdentifier r_;
    public static final ASN1ObjectIdentifier s_;
    public static final ASN1ObjectIdentifier t_;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier u_;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier v_;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier w_;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier x_;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier y_;
    public static final ASN1ObjectIdentifier z;
    public static final ASN1ObjectIdentifier z_;

    static {
        m_ = new ASN1ObjectIdentifier("1.2.840.113549.1.1");
        n_ = m_.b("1");
        o_ = m_.b("2");
        d = m_.b("3");
        e = m_.b("4");
        p_ = m_.b("5");
        q_ = m_.b("6");
        h = m_.b("7");
        r_ = m_.b("8");
        j = m_.b("9");
        k = m_.b("10");
        s_ = m_.b("11");
        t_ = m_.b("12");
        u_ = m_.b("13");
        v_ = m_.b("14");
        w_ = new ASN1ObjectIdentifier("1.2.840.113549.1.3");
        q = w_.b("1");
        x_ = new ASN1ObjectIdentifier("1.2.840.113549.1.5");
        y_ = x_.b("1");
        z_ = x_.b("4");
        u = x_.b("3");
        v = x_.b("6");
        w = x_.b("10");
        x = x_.b("11");
        y = x_.b("13");
        z = x_.b("12");
        A = new ASN1ObjectIdentifier("1.2.840.113549.3");
        B = A.b("7");
        C = A.b("2");
        D = A.b("4");
        E = new ASN1ObjectIdentifier("1.2.840.113549.2");
        F = E.b("2");
        G = E.b("4");
        H = E.b("5");
        I = E.b("7");
        J = E.b("8");
        K = E.b("9");
        L = E.b("10");
        M = E.b("11");
        N = new ASN1ObjectIdentifier("1.2.840.113549.1.7");
        O = new ASN1ObjectIdentifier("1.2.840.113549.1.7.1");
        P = new ASN1ObjectIdentifier("1.2.840.113549.1.7.2");
        Q = new ASN1ObjectIdentifier("1.2.840.113549.1.7.3");
        R = new ASN1ObjectIdentifier("1.2.840.113549.1.7.4");
        S = new ASN1ObjectIdentifier("1.2.840.113549.1.7.5");
        T = new ASN1ObjectIdentifier("1.2.840.113549.1.7.6");
        U = new ASN1ObjectIdentifier("1.2.840.113549.1.9");
        V = U.b("1");
        W = U.b("2");
        X = U.b("3");
        Y = U.b("4");
        Z = U.b("5");
        aa = U.b("6");
        ab = U.b("7");
        ac = U.b("8");
        ad = U.b("9");
        ae = U.b("13");
        af = U.b("14");
        ag = U.b("15");
        ah = U.b("16");
        ai = U.b("20");
        aj = U.b("21");
        ak = U.b("22.1");
        al = U.b("22");
        am = al.b("1");
        an = al.b("2");
        ao = U.b("23");
        ap = ao.b("1");
        aq = U.b("15.1");
        ar = U.b("15.2");
        as = U.b("15.3");
        at = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.1");
        au = at.b("2");
        av = at.b("4");
        aw = at.b("9");
        ax = at.b("23");
        ay = at.b("31");
        az = ah.b("3");
        aA = az.b("9");
        aB = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.6");
        aC = aB.b("1");
        aD = aB.b("2");
        aE = aB.b("3");
        aF = aB.b("4");
        aG = aB.b("5");
        aH = aB.b("6");
        aI = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.2");
        aJ = aI.b("1");
        aK = aI.b("4");
        aL = aI.b("5");
        aM = aI.b("10");
        aN = aI.b("11");
        aO = aI.b("12");
        aP = aI.b("47");
        aQ = aI.b("7");
        aR = aI.b("14");
        aS = aI.b("15");
        aT = aI.b("16");
        aU = aI.b("17");
        aV = aI.b("18");
        aW = aI.b("19");
        aX = aI.b("20");
        aY = aI.b("21");
        aZ = aI.b("22");
        ba = aI.b("23");
        bb = aI.b("24");
        bc = aI.b("25");
        bd = aI.b("26");
        be = aI.b("27");
        bf = aS;
        bg = aT;
        bh = aU;
        bi = aW;
        bj = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.1");
        bk = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.2");
        bl = new ASN1ObjectIdentifier("1.2.840.113549.1.12");
        bm = bl.b("10.1");
        bn = bm.b("1");
        bo = bm.b("2");
        bp = bm.b("3");
        bq = bm.b("4");
        br = bm.b("5");
        bs = bm.b("6");
        bt = bl.b("1");
        bu = bt.b("1");
        bv = bt.b("2");
        bw = bt.b("3");
        bx = bt.b("4");
        by = bt.b("5");
        bz = bt.b("6");
        bA = bt.b("6");
        bB = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.6");
        bC = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.7");
    }
}
