package org.spongycastle.asn1.x9;

import org.spongycastle.asn1.ASN1ObjectIdentifier;

/* compiled from: Twttr */
public interface X9ObjectIdentifiers {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier K;
    public static final ASN1ObjectIdentifier L;
    public static final ASN1ObjectIdentifier M;
    public static final ASN1ObjectIdentifier N;
    public static final ASN1ObjectIdentifier O;
    public static final ASN1ObjectIdentifier P;
    public static final ASN1ObjectIdentifier Q;
    public static final ASN1ObjectIdentifier R;
    public static final ASN1ObjectIdentifier S;
    public static final ASN1ObjectIdentifier T;
    public static final ASN1ObjectIdentifier U;
    public static final ASN1ObjectIdentifier V;
    public static final ASN1ObjectIdentifier W;
    public static final ASN1ObjectIdentifier X;
    public static final ASN1ObjectIdentifier Y;
    public static final ASN1ObjectIdentifier Z;
    public static final ASN1ObjectIdentifier a;
    public static final ASN1ObjectIdentifier aa;
    public static final ASN1ObjectIdentifier ab;
    public static final ASN1ObjectIdentifier ac;
    public static final ASN1ObjectIdentifier ad;
    public static final ASN1ObjectIdentifier ae;
    public static final ASN1ObjectIdentifier af;
    public static final ASN1ObjectIdentifier ag;
    public static final ASN1ObjectIdentifier ah;
    public static final ASN1ObjectIdentifier ai;
    public static final ASN1ObjectIdentifier aj;
    public static final ASN1ObjectIdentifier ak;
    public static final ASN1ObjectIdentifier b;
    public static final ASN1ObjectIdentifier c;
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier f;
    public static final ASN1ObjectIdentifier g;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;

    static {
        a = new ASN1ObjectIdentifier("1.2.840.10045");
        b = a.b("1");
        c = b.b("1");
        d = b.b("2");
        e = d.b("3.1");
        f = d.b("3.2");
        g = d.b("3.3");
        h = a.b("4");
        i = h.b("1");
        j = a.b("2");
        k = j.b("1");
        l = h.b("3");
        m = l.b("1");
        n = l.b("2");
        o = l.b("3");
        p = l.b("4");
        q = a.b("3");
        r = q.b("0");
        s = r.b("1");
        t = r.b("2");
        u = r.b("3");
        v = r.b("4");
        w = r.b("5");
        x = r.b("6");
        y = r.b("7");
        z = r.b("8");
        A = r.b("9");
        B = r.b("10");
        C = r.b("11");
        D = r.b("12");
        E = r.b("13");
        F = r.b("14");
        G = r.b("15");
        H = r.b("16");
        I = r.b("17");
        J = r.b("18");
        K = r.b("19");
        L = r.b("20");
        M = q.b("1");
        N = M.b("1");
        O = M.b("2");
        P = M.b("3");
        Q = M.b("4");
        R = M.b("5");
        S = M.b("6");
        T = M.b("7");
        U = new ASN1ObjectIdentifier("1.2.840.10040.4.1");
        V = new ASN1ObjectIdentifier("1.2.840.10040.4.3");
        W = new ASN1ObjectIdentifier("1.3.133.16.840.63.0");
        X = W.b("2");
        Y = W.b("3");
        Z = W.b("16");
        aa = new ASN1ObjectIdentifier("1.2.840.10046");
        ab = aa.b("2.1");
        ac = aa.b("3");
        ad = ac.b("1");
        ae = ac.b("2");
        af = ac.b("3");
        ag = ac.b("4");
        ah = ac.b("5");
        ai = ac.b("6");
        aj = ac.b("7");
        ak = ac.b("8");
    }
}
